### PR TITLE
[libxl] Write the backend-uuid for nic devices in

### PR DESCRIPTION
**Pull request by crogers1**
xenstore.

  OXT-1011

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Depends on https://github.com/OpenXT/xenclient-oe/pull/595 and https://github.com/OpenXT/xenclient-oe/pull/591

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/754

**Comment by crogers1** [comment]
Updated to also accept a devid as a param for network-attach.  This allows us to add/remove vifs precisely, and not rely on xl's strategy of using the next available devid.

**Comment by eric-ch** [comment]
With https://github.com/OpenXT/xenclient-oe/pull/609 handling the rebase of https://github.com/OpenXT/xenclient-oe/pull/603 and https://github.com/OpenXT/xenclient-oe/pull/591, this PR should be closed.

**Pull request closed without merging**
