### PR TITLE
Uprev the Linux 4.19 kernel from 4.19.32 to 4.19.44

### PR DESCRIPTION
**Pull request by rneilturner**
Signed-off-by: Richard Turner <turnerr@ainfosec.com>

OXT-1605

### CODE REVIEW

**Comment by eric-ch** [comment]
Can you refresh the defconfigs as well please? (Or is there no change?)

**Comment by eric-ch** [comment]
Build [$6566](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6566)

**Comment by rneilturner** [comment]
Updated the defconfig's, no significant changes.

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
