### PR TITLE
[qemu] fix debug typo

### PR DESCRIPTION
**Pull request by jean-edouard**
Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rianquinn** [comment]
is this associated with a bug, or was it just something you ran across?

**Comment by jean-edouard** [comment]
Every time I try to compile qemu with DEBUG_XEN it fails on that and I fix it manually.
I finally decided to submit a fix :)

**Comment by jean-edouard** [comment]
Rebased

**Comment by rossphilipson** [comment]
LGTM and it has been rebased now too. I think it is time...

**Pull request merged**
