### PR TITLE
OXT-462: TBoot upgrade to 1.9.5

### PR DESCRIPTION
**Pull request by eric-ch**
Upgrade to TBoot 1.9.5 and remove upstream/deprecated patches.

Add two patches for Linux kernel handling. Although this is not use in OpenXT (Xen being loaded as an ELF) I believe this is useful to test TBoot on its own when debugging things.

OXT-462

### CODE REVIEW

**Comment by eric-ch** [comment]
Rebased.

**Comment by jean-edouard** [comment]
LGTM, tested on a laptop and a desktop, merging soon.

**Comment by jean-edouard** [comment]
Actually I just found a small issue with this.
While everything seems to work fine, I get this message at the end of the installation:
`stages/Commit-main: line 47: tb_polgen: not found`

I'll wait until it's fixed to merge.

**Comment by eric-ch** [comment]
I did not add the relevant RDEPENDS when rebasing on master... my bad. I'll start a build with that in for tomorrow.

**Comment by rneilturner** [comment]
+1 Tested the latest RDEPENDS commit on a Dell SkyLake 7040 without issue.

**Comment by rossphilipson** [comment]
Excellent, thanks for the validation (and the PR too). Merging soon.

**Pull request merged**
