### PR TITLE
libsemanage: remove runtime dependency on python

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
LGTM, can you PR against stable-8 as well please?
Upstream submission: https://lists.yoctoproject.org/pipermail/yocto/2018-May/041319.html).

**Comment by jean-edouard** [comment]
https://github.com/OpenXT/xenclient-oe/pull/909

**Comment by jean-edouard** [comment]
Build here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1531

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
