### PR TITLE
xen-libxl patch cleanup

### PR DESCRIPTION
**Pull request by jandryuk**
I noticed some unnecessary changes in our libxl patches which are removed in this series.

@crogers1 Is there a particular reason for changing "/local/domain/N/control" to rw perms https://github.com/OpenXT/xenclient-oe/commit/db804d91b4d16e498ef8656094ddfc403933c546#diff-83c581625019ac0b6ff2913055c602acR52?  You introduced it originally, but I don't think it's necessary.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/#/builders/1/builds/7047

**Comment by jean-edouard** [comment]
@crogers1, please review.

**Comment by crogers1** [comment]
@jandryuk Sorry for the late review, I missed these notifications.

For the /local/domain/N/control changes, I popped back to the xen 4.6.1 release and looked around for them and couldn't find error, drivers, attr, or messages, so I likely introduced them for that reason.  Xen 4.12 looks like it doesn't have "error" or "messages" set, so you may need to keep those?  Or perhaps they aren't needed at all anymore.

At some point it looks like they split out the vkb/vfb creation, so that commit is fine to drop the redundant code.  Yea overall, looks good.  Once again, sorry for the delay.

**Comment by jandryuk** [comment]
Thanks, @crogers1 

For "error" and "messages", yes, those get dropped.  They are unused on my systems, and are a relic of xenvm, AFAICT.  I should update the commit message to mention that.

**Comment by jandryuk** [comment]
Pushed with an amended commit message for "xen: Remove duplicate xenstore writes " mentioning the removal of "error" and "messages" nodes.

**Comment by eric-ch** [comment]
With no diff post force-push: Will merge soon.

**Comment by jandryuk** [comment]
Making `control` read-only breaks qemu-dm's acpi power-off.  qemu-dm cannot write to `/local/domain/$domid/control/hvm-powerbutton-enable`.  Xenmgr doesn't see that node, so it doesn't write `"/local/domain/" ++ domid ++ "/control/hvm-shutdown") "poweroff"` to trigger the acpi path and defaults to `"xl shutdown -c -w " ++ domid`.

Options:
 - Revert the control permission change.
 - Have libxl create `control/hvm-powerbutton-enable` so it's writable with value "0".  Xenmgr would then need to be a little smarter to ensure the value is "1" before using that shutdown path.
 - Drop "control/hvm-powerbutton-enable" and just make it always available.  That means ACPI must always be available.  Not totally unreasonable since ACPI is basically always used nowadays.
 - Have qemu-dm write to its own xenstore, and have Xenmgr check there instead of in the guest.  Use a writable path under "device-model"?

I think I'm leaning toward the last option.

**Pull request merged**
