### PR TITLE
OXT-1649: linux: Add PVH support config for UIVM.

### PR DESCRIPTION
**Pull request by eric-ch**
UIVM does not have hard limitation to run as a PVH guest.
Add the relevant kernel configuration to handle that use-case.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6668

**Comment by jean-edouard** [comment]
What happened here? Was the UIVM defconfig inappropriately based on a (very) different kernel version?

**Comment by eric-ch** [comment]
@jean-edouard No quite sure what you mean, here are a couple of answers I could give you for the changes in the defconfig:

- CONFIG_GCC_VERSION, CONFIG_PLUGIN_HOSTCC, etc: this is because the previous defconfig was refreshed in a non-oe environment, the OE build environment would redefine this anyway.
- CONFIG_XEN_PVH has its dependencies. CONFIG_PCI, which comes with some bagage, e,g. CONFIG_ACPI, which has a few dependencies as well.
- CONFIG_XEN_BACKEND is not required in UIVM.

Here is the list of the enabled configuration by this PR:
```
+CONFIG_CC_HAS_ASM_GOTO=y
+CONFIG_XEN_PVHVM=y
+CONFIG_XEN_PVHVM_SMP=y
+CONFIG_XEN_PVH=y
+CONFIG_PM_CLK=y
+CONFIG_ACPI=y
+CONFIG_ACPI_LEGACY_TABLES_LOOKUP=y
+CONFIG_ARCH_MIGHT_HAVE_ACPI_PDC=y
+CONFIG_ACPI_SYSTEM_POWER_STATES_SUPPORT=y
+CONFIG_ACPI_SPCR_TABLE=y
+CONFIG_ACPI_LPIT=y
+CONFIG_ACPI_REV_OVERRIDE_POSSIBLE=y
+CONFIG_ACPI_PROCESSOR_CSTATE=y
+CONFIG_ARCH_HAS_ACPI_TABLE_UPGRADE=y
+CONFIG_ACPI_HOTPLUG_IOAPIC=y
+CONFIG_HAVE_ACPI_APEI=y
+CONFIG_HAVE_ACPI_APEI_NMI=y
+CONFIG_X86_PM_TIMER=y
+CONFIG_PCI=y
+CONFIG_PCI_DIRECT=y
+CONFIG_PCI_XEN=y
+CONFIG_PCI_DOMAINS=y
+CONFIG_PCI_QUIRKS=y
+CONFIG_PCI_LABEL=y
+CONFIG_AMD_NB=y
+CONFIG_HAVE_CLK=y
+CONFIG_BLK_MQ_PCI=y
+CONFIG_PNP=y
+CONFIG_PNP_DEBUG_MESSAGES=y
+CONFIG_PNPACPI=y
+CONFIG_DEVPORT=y
+CONFIG_POWER_SUPPLY=y
+CONFIG_THERMAL=y
+CONFIG_THERMAL_DEFAULT_GOV_STEP_WISE=y
+CONFIG_THERMAL_GOV_STEP_WISE=y
+CONFIG_VGA_ARB=y
+CONFIG_XEN_AUTO_XLATE=y
+CONFIG_XEN_ACPI=y
+CONFIG_PMC_ATOM=y
+CONFIG_CLKDEV_LOOKUP=y
+CONFIG_HAVE_CLK_PREPARE=y
+CONFIG_COMMON_CLK=y
+CONFIG_RATIONAL=y
```

I think we can remove the following:
```
CONFIG_ACPI_SPCR_TABLE
CONFIG_THERMAL
CONFIG_POWER_SUPPLY
```

**Comment by jean-edouard** [comment]
Thanks for the grep, makes it less scary :)
I initially expected this PR to be more or a less a 1-liner (like `CONFIG_XEN_PVH=y`), didn't realize that change was so invasive, but now I get it.
Merging soon.

**Comment by eric-ch** [comment]
#### v2:
- Removed: `CONFIG_ACPI_SPCR_TABLE`, `CONFIG_THERMAL`, `CONFIG_POWER_SUPPLY`.

**Pull request merged**
