### PR TITLE
[xen] Pull in upstream patch to support xsave on Skylake.

### PR DESCRIPTION
**Pull request by jctemkin**
This patch was originally posted on the Qubes mailing list for Xen 4.4, and has been backported to Xen 4.3.4.

### CODE REVIEW

**Comment by jean-edouard** [comment]
https://openxt.atlassian.net/browse/OXT-568

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/72
Installed successfully on Skylake! :)
Now I get this error that I also got with a Xen-ified Debian:

    [    0.000000] IOAPIC[0]: Unable to change apic_id!

Do you know about that one?

Either way, I think this PR is good to go, will merge tomorrow.

**Comment by jctemkin** [comment]
Excellent, glad hear the install went well :) However, that apic message is totally new to me, sorry! Hopefully the fix isn't too difficult to find.

**Comment by rianquinn** [comment]
You might want to check to see if your hardware supports changing the APIC ID, as that is not supported on all hardware

**Comment by jean-edouard** [comment]
@rianquinn I'm not sure how to check that, I'm using a Dell E7470.
However I looked at the code and the error should not be fatal... I'll keep looking.

**Comment by jean-edouard** [comment]
Nevermind, the machine was still running Debian when I saw the error... Sorry.

**Comment by rianquinn** [comment]
My guess is your fine. The only way I know to check would be to write the code to try and change it. But this is from the Intel Manual (section 10.4.6): 

> In MP systems, the local APIC ID is also used as a processor ID by the BIOS and the operating system. Some processors permit software to modify the APIC ID. However, the ability of software to modify the APIC ID is processor model specific. Because of this, operating system software should avoid writing to the local APIC ID register.

**Comment by jean-edouard** [comment]
Thank you @rianquinn.
I got OpenXT to boot to the UI after installing correctly :)

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
