### PR TITLE
Allow PCI USB3 keyboards (most 2-in-1 keyboards) to be used for reseal.

### PR DESCRIPTION
**Pull request by ktemkin**

### CODE REVIEW

**Comment by cjp256** [comment]
LGTM, though missing signoff. :)

**Comment by jean-edouard** [comment]
+1

**Comment by rossphilipson** [comment]
I commented on a priv chan about this:

> ktemkin: i am fine with that though given that the pci glue drivers depend on the hcd drivers maybe we should just modprobe all the *hci-pci.ko drivers instead
> that should drag up all the *hci-hcd.ko drivers and all the other dependencies
> on debian they just cut out the middle man and build the pci glue right into the hcd driver

**Comment by jean-edouard** [comment]
I tested with just those 4 (see below), and both the integrated laptop keyboard and the one on the USB3 port worked fine. As Ross suggested, *hci-pci depend on *hci-hcd (apart from uhci, that includes the pci bits inside the hcd driver).

     modprobe ehci-pci
     modprobe uhci-hcd
     modprobe ohci-pci
     modprobe xhci-pci

**Comment by ktemkin** [comment]
@rossphilipson: I agree-- I'll update the patch.
@jean-edouard: Thanks for testing; I'll update the PR accordingly. :+1

**Comment by ktemkin** [comment]
Modified per the suggestions above.

**Comment by rossphilipson** [comment]
Thanks for fixing that. That is what Jed tested so I think this can go in. Will merge soon...

**Pull request merged**
