### PR TITLE
OXT-1233: Uprev wpa-supplicant from 0.7.3 to 2.6

### PR DESCRIPTION
**Pull request by rneilturner**
Signed-off-by: Richard Turner <turnerr@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [#1228](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1228)

**Comment by eric-ch** [comment]
LGTM, will merge soon.

**Comment by richpersaud** [comment]
If this merge will result in any existing patches being dropped, please create a JIRA ticket to document any impact on functionality, so we can determine if the patches later need to be ported.

**Comment by eric-ch** [comment]
@richpersaud The ticket is updated with documentation regarding the patches that are removed by this PR.
Unless anyone has another concern regarding this: Will merge soon.

**Comment by eric-ch** [comment]
Will merge very soon if no further question.

**Pull request merged**
