### PR TITLE
STABLE-7: OXT-580: syslinux mobile broadband

### PR DESCRIPTION
**Pull request by eric-ch**
Update mobile-broadband-provider-info.
Upgrade syslinux.

### CODE REVIEW

**Comment by rossphilipson** [comment]
@eric-ch should there be a master version of this too?

**Comment by eric-ch** [comment]
@rossphilipson there is: https://github.com/OpenXT/xenclient-oe/pull/592

**Comment by rossphilipson** [comment]
Tested on master, LGTM. Will merge with RM sign off

**Comment by richpersaud** [comment]
Is there a known-good version of pxelinux.0 that is compatible with this stable7 version of syslinux and the syslinux version in stable6?

**Comment by eric-ch** [comment]
@richpersaud pxelinux.0 is built from the syslinux recipe, therefor it is 6.03 (stable-7 & master) or 4.04 (stable-6). So, you ca either PXE boot pxelinux.0 4.04 (packaged with a stable-6 build in the netboot dir) or a pxelinux.0 6.03 (packaged with a stable-7 or master build in the netboot dir).
If the goal is to test PXE installation of stable-6 vs stable-7 from one PXE menu, you should be able to chain-load from your pxe-server pxelinux.0 to the one that is packaged with the tested build.

**Comment by richpersaud** [comment]
Could we add pxelinux.0 to the netboot directory?  Not seeing it there currently.

**Pull request merged**
