### PR TITLE
seal-system: fix the PCRs order

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by tklengyel** [comment]
What was wrong with the current way? Is the order of `-p` flags not position independent?

**Comment by jean-edouard** [comment]
@tklengyel yes it does seem like the order matters. This PR effectively fixes forward sealing for me (at least on legacy installs).

**Comment by tklengyel** [comment]
I ran a small test in which I created two encrypted files with `tpm_sealdata_sa -i ./test.txt -o ./first -z -p 1 -p 2` and `tpm_sealdata_sa -i ./test.txt -o ./second -z -p 2 -p 1`. Both unseal just fine.

**Comment by jean-edouard** [comment]
Yeah but you used the same order for seal and unseal no?

**Comment by tklengyel** [comment]
Unseal doesn't use any order.

**Comment by dpsmith** [comment]
@jean-edouard and @tklengyel, I am not sure how it is making a difference, here[1](xenclient-oe/recipes-openxt/tpm-tools/files/tpm-tools-standalone.patch) is where we add the capability for TPM 1.2. Its not seen in the patch but you can go look at the tpm-tools code, which creates a PCR Composite structure which is more or less a key/value structure of PCR and its value.

**Comment by jean-edouard** [comment]
I don't have a TPM1.2 machine handy, but here's what I mean on a TPM2.0:
```
root@xenclient-dom0:/storage# echo stuff > testroot@xenclient-dom0:/storage# tpm2_sealdata -H 0x81000000 -I test -O key -o key.pub -g 0xB -G 8 -b 0x492 -r 0 -r 1
inSensitive.t.sensitive.data.t.size = 6
nameAlg = 0x000b
type = 0x0008
ObjectAttribute: 0x00000492

Create Object Succeed !
FlushContext failed for handle, non-fatal
root@xenclient-dom0:/storage# tpm2_unsealdata -H 0x81000000 -n key -u key.pub -g 0xB -r 1 -r 0
build_pcr_policy, Error Code: 0x1c4
build_policy() failed, ec: 0x1c4
root@xenclient-dom0:/storage# tpm2_unsealdata -H 0x81000000 -n key -u key.pub -g 0xB -r 0 -r 1
stuff
root@xenclient-dom0:/storage# 
```

**Comment by tklengyel** [comment]
Interesting, `build_pcr_policy` make use of `hash_sequence_ex` that looks like makes the order relevant.

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
