### PR TITLE
OXT-1124: updatemgr: SELinux perms to read ssl certs files.

### PR DESCRIPTION
**Pull request by eric-ch**
Authorize updatemgr to read certificates and configuration required for
openssl.

### CODE REVIEW

**Comment by eric-ch** [comment]
Building: [923](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/923)

**Comment by rossphilipson** [comment]
Built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/924

**Comment by rossphilipson** [comment]
Tested build 929 with the latest fixes. It still does not work - lvcreate is failing but not because of SELinux.

**Comment by eric-ch** [comment]
Building: [936](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/936), this should attend the last issues.

**Comment by rossphilipson** [comment]
Latest build:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/936
Testing now...

**Comment by eric-ch** [comment]
I missed something in the lvm2 package again...
Building again: [938](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/938)

**Comment by eric-ch** [comment]
This should be considered tied to:
- https://github.com/OpenXT/xenclient-oe/pull/675
- https://github.com/OpenXT/installer/pull/37

**Comment by rossphilipson** [comment]
Tested on 942 (master custom), LGTM, merging soon.

**Pull request merged**
