### PR TITLE
libxl: fix  "xl save" by allowing vNUMA-enabled guests to be saved

### PR DESCRIPTION
**Pull request by Jafaral**
Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1547

**Comment by jean-edouard** [comment]
I tried this and got the following XSA denials:
```
(XEN) avc:  denied  { get_vnumainfo } for domid=0 target=5 scontext=system_u:system_r:dom0_t tcontext=system_u:system_r:hvm_guest_t tclass=domain2
(XEN) avc:  denied  { disable } for domid=0 target=5 scontext=system_u:system_r:dom0_t tcontext=system_u:system_r:hvm_guest_t tclass=shadow
```
Do you want me to PR a fix for these?

**Comment by Jafaral** [comment]
@jean-edouard Sure. I expected this would be the next thing to look at after this PR and the XenMgr PR.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1562

**Pull request merged**
