### PR TITLE
STABLE-7: OXT-1094: Xen 4.6.5 micro-upgrade and latest XSA

### PR DESCRIPTION
**Pull request by eric-ch**
Upgrade to the latest micro-release of Xen.
Backport the XSA that are still not upstream.

### CODE REVIEW

**Comment by eric-ch** [comment]
https://github.com/OpenXT/openxt/pull/246

**Comment by rossphilipson** [comment]
Building here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/854

**Comment by rossphilipson** [comment]
Disregard that other build, built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/856

**Comment by rossphilipson** [comment]
LGTM, will merge with RM signoff.

**Pull request merged**
