### PR TITLE
SyncVM fixes

### PR DESCRIPTION
**Pull request by jandryuk**
The syncvm image is a little broken.  This PR provides some fixes.

syncvm was using the default SELinux fstab.early, but syncvm doesn't run SELinux.  Additionally, the regular fstab was incorrect.  Fix up both of those.  One symptom was sshd failed to start, so you couldn't sshv4v in.

We also have some fixes for setting up volatiles.

sync-client wasn't running since pyicbinn couldn't import importlib.  Fix that dependency.

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [$6634](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6634)

**Comment by jandryuk** [comment]
Here are some python commands to exercise icbinn from syncvm.
```
import pyicbinn
i=pyicbinn.icbinn_clnt_create_v4v(0,4878)
pyicbinn.icbinn_mkdir(i, "foo")
pyicbinn.icbinn_readent(i, ".", 0)
pyicbinn.icbinn_readent(i, ".", 1)
#.... you can repeat, incrementing the last number until you get None
pyicbinn.icbinn_rmdir(i, "foo")
# fails for me with -13 (EACCES) since SELinux denies it in dom0
```

You may have to add icbinn-path to the syncvm configuration:
`xec-vm -n syncvm set icbinn-path "/storage/sync/syncvm,/config/sync/syncvm"`
You may also need to create & label those directories in dom0.  You only need the first path for this test, I think.

**Comment by eric-ch** [comment]
@jandryuk Thanks for the test steps!

Unfortunately that did not go too well...
```python
>>> import pyicbinn
>>> i = pyicbinn.icbinn_clnt_create_argo(0, 4878)
>>> pyicbinn.icbinn_mkdir(i, "foo")
Segmentation fault
```
```
VM syncvm (3): [62487.444393] python[590]: segfault at 0 ip 00007f75d43d5719 sp 00007ffce71859c0 error 4 in _pyicbinn.so[7f75d43c9000+1c000]
VM syncvm (3): [62487.444421] Code: 74 14 8b 08 31 d2 85 c9 74 05 8b 50 04 f7 da 89 d0 48 83 c4 18 c3 ba ff ff ff ff eb f2 0f 1f 40 00 48 83 ec 18 48 89 74 24 08 <48> 8b 37 48 8d 44 24 08 48 89 c7 e8 57 bf ff ff 48 85 c0 74 14 8b
```

Nevertheless, I do not think that PR introduced this behavior as it does not change icbinn implementation.
I will open a new ticket and, if no one opposes, this can be merged.

**Comment by jandryuk** [comment]
Oh, right.  I think you need these PRs in addition to this one:
https://github.com/OpenXT/xenclient-oe/pull/1197
https://github.com/OpenXT/icbinn/pull/5

**Comment by eric-ch** [comment]
@jandryuk Oh, my apologies, I must be missing https://github.com/OpenXT/icbinn/pull/5 .

**Comment by eric-ch** [comment]
Will merge when comments on https://github.com/OpenXT/xenclient-oe/pull/1197 are addressed.

@crogers1 This should probably go to stable-9 as well?

**Comment by crogers1** [comment]
@eric-ch Yes, this and https://github.com/OpenXT/xenclient-oe/pull/1197

**Comment by eric-ch** [comment]
Build [$6659](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6659)

**Comment by eric-ch** [comment]
LGTM, this should go with:
- https://github.com/OpenXT/xenclient-oe/pull/1197
- https://github.com/OpenXT/icbinn/pull/5

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
