### PR TITLE
S9: lvm2: Configuration packaging.

### PR DESCRIPTION
**Pull request by eric-ch**
With `rm_work.bbclass`, rebuilding the installer image will fail since the `install-lvm.conf` will be deleted after `xenclient-installer-image`:
```
| DEBUG: Executing shell function write_installer_config_files
| install: cannot stat ‘[...]/tmp-glibc/work/openxt_installer-oe-linux/xenclient-installer-image/1.0-r15/installer-lvm.conf
```

This is fixed in master by providing the lvm.conf files through different recipes (https://github.com/OpenXT/xenclient-oe/pull/1249). Backport the fix.

No functional change.

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [$7087](http://openxt-builder.ainfosec.com:8010/#/builders/1/builds/7087)

**Comment by jandryuk** [comment]
Will merge soon

**Comment by dpsmith** [comment]
Is there any reason this cannot be merged?

**Comment by jandryuk** [comment]
I thought I pinged @crogers1 to approve, but I don't see it here. Does he need to approve everything for stable-9?

**Comment by dpsmith** [comment]
True, he is release manager so he should approve before it goes in.

**Comment by jandryuk** [comment]
Thanks, @crogers1 .  Will merge soon.

**Pull request merged**
