### PR TITLE
OXT-1360: QEMU 2.12

### PR DESCRIPTION
**Pull request by jandryuk**
The PR starts moving files to an un-versioned qemu-dm directory and normalizing the patch contents.  Then the patches "qemu-dm: 2.12 <patch name>" show a patch-by-patch conversion for 2.12.  They are mostly straightforward. More substantial ones are:  

https://github.com/OpenXT/xenclient-oe/commit/e5cbac565da08ac3e7f2a21edc0bdc3ede6b7010 has a fairly significant re-write
https://github.com/OpenXT/xenclient-oe/commit/a3b233ff46aaf5cb6403738d55147d3e33c80bc1 has some non-trivial changes.

The patches after that are more functional fixes and changes.

ATAPI support is untested since I don't have a machine with a CD drive.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1579

**Comment by jean-edouard** [comment]
This is really cool, thanks!
I just tried the build with a Windows 10 guest, and it boots fine with and without tools, with and without a stubdom.
I'll do more testing today but I think this is good to go no matter what!
+1

**Comment by jandryuk** [comment]
Thanks.  If you can test ATAPI, that would be great.  My devices don't have a CD-ROM, so it is untested.  The ATAPI code didn't change much to build though.

**Comment by jean-edouard** [comment]
ATAPI works fine, merging soon!

**Comment by jandryuk** [comment]
Great.  Thanks for testing!

**Pull request merged**
