### PR TITLE
Xen 4.11 Read-only IDE fix

### PR DESCRIPTION
**Pull request by jandryuk**
This PR fixes libxl-support-hvm-readonly-disks.patch after the 4.11 uprev for read-only IDE support.  You can see this with HVM NDVM.

It also cleans up the patch to drop the changes to COLO since we don't use or support that functionality.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Oops, my bad, thanks for the fix. Building soon.

**Comment by jandryuk** [comment]
No problem.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1885

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
