### PR TITLE
Removing dm-wrapper recipes for OXT-691

### PR DESCRIPTION
**Pull request by dpsmith**
dm-wrapper is not being used and the repository has been retired.
Removing the recipes so that bitbake parsing will not fail.

### CODE REVIEW

**Comment by rossphilipson** [comment]
Sorry about that one - we lose the github magic when we use the new scripts and mirrors. LGTM.

**Comment by jean-edouard** [comment]
This should be a cherry-pick of https://github.com/OpenXT/xenclient-oe/pull/347, I can take care of it if you wish.

**Comment by dpsmith** [comment]
Go right ahead.



V/r,

Daniel P. Smith

Apertus Solutions, LLC

410-846-4564






---- On Mon, 01 Aug 2016 09:47:21 -0400 Jed &lt;notifications@github.com&gt;wrote ---- 




This should be a cherry-pick of #347, I can take care of it if you wish.

**Comment by jean-edouard** [comment]
Replaced by https://github.com/OpenXT/xenclient-oe/pull/377. Closing.

**Pull request closed without merging**
