### PR TITLE
refpolicy-mcs: replace OpenXT file creation patches by the files themselves

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
The patch is pretty big. For review purposes, it might be easier to visually compare these two:
https://github.com/OpenXT/xenclient-oe/tree/master/recipes-security/refpolicy
https://github.com/jean-edouard/xenclient-oe/tree/refactor_refpolicy/recipes-security/refpolicy

According to my tests, the end results (the patched refpolicies) are exactly the same, but don't take my word for it!

**Comment by stephensmalley** [comment]
I see a difference in alsa.te:

-optional_policy(`
-	statusreport_create_tmp_files(alsa_t)
-	statusreport_write_tmp_files(alsa_t)
-	statusreport_getattr_tmp_files(alsa_t)
-')
-

Seems to have been dropped from statusreport-interfaces.diff.

**Comment by jean-edouard** [comment]
My bad, this chunk was giving me trouble so I removed it and forgot to put it back...
Good catch, thanks!
Commit amended.

**Comment by stephensmalley** [comment]
Ok, now I get the same result from building both.
Also looks like the split is correct.
We may want to migrate handling of modules.conf (from patch to separately managed file) at some point; for example, Red Hat ships their own complete modules.conf with a specific list of policy modules they want included for each of their policy variants and just drops that into the refpolicy directory.  Otherwise you may be picking up additional modules from refpolicy each time you rebase without really wanting them in your policy.

**Comment by rossphilipson** [comment]
@stephensmalley that sounds like wise advice and a good candidate for a ticket.

**Comment by stephensmalley** [comment]
+1

**Comment by eric-ch** [comment]
LGTM, +1.
Will merge soon.

**Pull request merged**
