### PR TITLE
[tpm2.0] Fix arg parsing when passing in hash for

### PR DESCRIPTION
**Pull request by crogers1**
forward sealing.

  OXT-1155

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
@jean-edouard Hold off on this for a sec, I missed an edge case.

**Comment by crogers1** [comment]
3 issues solved here:

1) Fixed strtok logic so that it advances past the pcr id in the -r param, to read the forward hash.
2) In forward hash case, forgot to set pcrValues[i].t.size, causing the resulting pcrDigest to be calculated improperly.  This can be seen when forward sealing to all 0's, and having unseal fail even when the pcr is all 0's.
3) Removed the ability to pass a forward hash to tpm2_unsealdata, as that's not something we want the platform to be able to perform.

**Comment by eric-ch** [comment]
building: [976](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/976)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1000
Merging soon.

**Pull request merged**
