### PR TITLE
[qemu-dm] try take the vga lock (or do nothing) when drawing graphics

### PR DESCRIPTION
**Pull request by jean-edouard**
Modify and use the vga (spin)lock so that we don't draw graphics (and potentially resize) while the vgabios is working (most likely handling a modeset).

OXT-123

Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
+1 but I would like some other folks to take a look too.

**Comment by jean-edouard** [comment]
Added a commit to take the lock earlier and increment the PR, as per @ktemkin recommendations.

**Comment by cjp256** [comment]
Will test latest.

**Comment by cjp256** [comment]
+1, I don't have repro of the test case, but VMs seem to be booting fine with these patches.

**Pull request merged**
