### PR TITLE
Update Linux kernels to 3.18.24

### PR DESCRIPTION
**Pull request by eric-ch**
Port patches and configurations of VM kernels to latest 3.18.24.

### CODE REVIEW

**Comment by jean-edouard** [comment]
We still have machine-specific patches? I thought we got rid of those...
Can you maybe look into it for this update?

**Comment by eric-ch** [comment]
@jean-edouard Yes 2 for dom0, they've been here for a while. I'll put that in the common patch-queue.

**Comment by jean-edouard** [comment]
\o/ you're the best

**Comment by eric-ch** [comment]
This has been dormant too long. Will rebase an make a new PR.

**Pull request closed without merging**
