### PR TITLE
kernel: enable cgroups for dom0

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1379

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jandryuk** [comment]
What about dropping the revert patch and just mounting the memory cgroup at '/sys/fs/cgroup/memory'?

blktap will use the cgroup in dom0.  Is there a use for uivm or ndvm?

**Comment by jean-edouard** [comment]
Good questions!

About the first one, I would have to first mount a tmpfs in /sys/fs/cgroup, then mkdir /sys/fs/cgroup/memory, then mount the cgroup there, which can't all be done in fstab and would have to be hardcoded somewhere like mountall.sh. Also that's just not what's usually done out there. You either have systemd and the separate dirs, or sysvinit and the one directory.

About the second one, I just followed what the ticket said, but you're right, this is probably not really needed in service VMs. I'll ask the author @eric-ch about it :)

**Comment by jandryuk** [comment]
Makes sense on the systemd vs. sysvinit cgroups.  If more software starts requiring the systemd layout, then we may want to match that layout in the future.

I think you want to split your commit into 2 or 3.  One enables cgroups in the kernel, and the second (or rolled into the previous one) adds the fstab entry.  That would be OXT-1379.  The other commit would change blktap under OXT-1312.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6555

**Comment by eric-ch** [comment]
@jean-edouard The ticket was a blanket statement. I do not think there is anything using cgroups in UIVM or NDVM currently.

**Comment by jean-edouard** [comment]
Fixed, dom0 only now.

**Comment by eric-ch** [comment]
Build [$6596](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6596)

**Comment by jean-edouard** [comment]
Do not merge, AVCs spotted...

**Comment by jean-edouard** [comment]
Tapdisk AVCs fixed.
For the mount AVCs, see https://github.com/OpenXT/xenclient-oe/pull/1149#issuecomment-501381058

**Comment by eric-ch** [comment]
Build [$6607](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6607)

**Comment by eric-ch** [comment]
Will merge soon.

@crogers1 Is this something you want in stable-9?

**Comment by crogers1** [comment]
@eric-ch sure, let's bring it into stable-9

**Pull request merged**
