### PR TITLE
STABLE-6: qemu: fix iso media change code

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-372
OXT-632

Signed-off-by: Jed <lejosnej@ainfosec.com>
(cherry picked from commit 95161396585b2776a378be1656346cdce6eac50d)
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
This is not "approved" for stable-6 yet, but I think it would make sense there.

**Comment by eric-ch** [comment]
+1, I think it should go in stable-6 as well.

**Comment by jean-edouard** [comment]
There is an issue with this PR, see https://github.com/OpenXT/xenclient-oe/pull/375
I will update it once the above PR is +1ed.
Please do not merge this just yet.

**Comment by jean-edouard** [comment]
Fix added.

**Comment by rossphilipson** [comment]
+1

**Comment by rossphilipson** [comment]
@eric-ch I think you were going to test this one - how is it looking?

**Comment by eric-ch** [comment]
@rossphilipson Good! Already merged in master, merging now

**Pull request merged**
