### PR TITLE
linux-firmware: install all bnx2 firmware files

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
That makes sense to me. I will leave it open for a spell in case anybody else has any comments.

**Comment by cjp256** [comment]
@dozylynx your upstream patch got pulled into oe-core, any plans on resolving #279 ?

**Comment by dozylynx** [comment]
@cjp256 : yes, will work on that shortly.

@jean-edouard : What motivated this PR to install all the bnx2 firmware files?

**Comment by jean-edouard** [comment]
@dozylynx I tried to use a bnx2 NIC and NDVM failed to find the firmware file for it.
I saw we're installing just 1 bnx2 firmware file, which makes no sense to me. I think it should be either all or none.

**Comment by dozylynx** [comment]
@jean-edouard : hmm, this looks pretty unfortunate, since the patch that I sent upstream into oe-core only installs the single most-recent mips firmware file and packages it as a bnx2-mips package, which we can then pull in. I suppose the proper fix is to revise (and rename) that upstream package to install all the bnx2 firmwares. Are you up for doing that?

**Comment by dozylynx** [comment]
I'm reestablishing my build environment at the moment. Below is an untested, unbuilt draft patch for upstream to package all the bnx2 firmware. The downside is that it installs 1.5MB of firmware instead of 102KB.

```
diff --git a/meta/recipes-kernel/linux-firmware/linux-firmware_git.bb b/meta/recipes-kernel/linux-firmware/linux-firmware_git.bb
index 95a57d7..59a905a 100644
--- a/meta/recipes-kernel/linux-firmware/linux-firmware_git.bb
+++ b/meta/recipes-kernel/linux-firmware/linux-firmware_git.bb
@@ -230,7 +230,7 @@ PACKAGES =+ "${PN}-ralink-license ${PN}-ralink \
              ${PN}-iwlwifi-7265d ${PN}-iwlwifi-8000c ${PN}-iwlwifi-8265 \
              ${PN}-i915-license ${PN}-i915 \
              ${PN}-adsp-sst-license ${PN}-adsp-sst \
-             ${PN}-bnx2-mips \
+             ${PN}-bnx2 \
              ${PN}-whence-license \
              ${PN}-license \
              "
@@ -430,18 +430,20 @@ RDEPENDS_${PN}-bcm43340 += "${PN}-broadcom-license"
 RDEPENDS_${PN}-bcm4339 += "${PN}-broadcom-license"
 RDEPENDS_${PN}-bcm4354 += "${PN}-broadcom-license"
 
-# For Broadcom bnx2-mips
+# For Broadcom bnx2
 #
 # which is a separate case to the other Broadcom firmwares since its
 # license is contained in the shared WHENCE file.
 
-LICENSE_${PN}-bnx2-mips = "WHENCE"
+LICENSE_${PN}-bnx2 = "WHENCE"
 LICENSE_${PN}-whence-license = "WHENCE"
 
-FILES_${PN}-bnx2-mips = "/lib/firmware/bnx2/bnx2-mips-09-6.2.1b.fw"
+FILES_${PN}-bnx2 = " \
+  /lib/firmware/bnx2/*.fw \
+"
 FILES_${PN}-whence-license = "/lib/firmware/WHENCE"
 
-RDEPENDS_${PN}-bnx2-mips += "${PN}-whence-license"
+RDEPENDS_${PN}-bnx2 += "${PN}-whence-license"
 
 # For iwlwifi
 LICENSE_${PN}-iwlwifi-135-6     = "Firmware-iwlwifi_firmware"
```

**Comment by dozylynx** [comment]
ok, my change is in upstream master but not the jethro branch, so it's not of immediate help to us anyway.

I propose this plan:
* @jean-edouard to verify that this change does actually fix his NICs first. If not, we can drop this PR.
* assuming ok, @jean-edouard to merge this PR.
* I'll rebase my #279 PR and change it to install all the bnx2 firmware.
* I'll also submit a change to upstream to package all the bnx2 firmware files and not just the most recent mips one.

When the upstream change is accepted into a branch that we're tracking -- possibly we'll have to make a merge request for it -- then we'll be able to switch to using the upstream packaging and drop our local changes.

**Comment by dozylynx** [comment]
ok, I've included the change to install _all_ bnx2 firmwares in the latest revision of PR #279 , so if that's accepted then this PR is no longer required.

**Comment by jean-edouard** [comment]
Thank you @dozylynx, closing.

**Pull request closed without merging**
