### PR TITLE
Update the Intel microcode dated 20180108

### PR DESCRIPTION
**Pull request by rneilturner**
Signed-off-by: Richard Turner <turnerr@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1292

**Comment by dpsmith** [comment]
I would be cautious about a blanket update of intel microcode. Intel has [warned](https://newsroom.intel.com/news/intel-security-issue-update-addressing-reboot-issues/) that they are having issues with microcode on pre-skylake.

**Comment by rneilturner** [comment]
@dpsmith we are going a test event over the next few weeks with the microcode change. We can leave the PR open until we do our full analysis, posting any exceptions we find.

**Comment by dpsmith** [comment]
Advice from Intel:
"We recommend that OEMs, cloud service providers, system manufacturers, software vendors and end users stop deployment of current versions, as they may introduce higher than expected reboots and other unpredictable system behavior."[[1](https://newsroom.intel.com/news/root-cause-of-reboot-issue-identified-updated-guidance-for-customers-and-partners/)]

I would recommend holding off on the merging of this PR and updated it with new microcode that should hopefully be coming out in soon.

**Comment by rneilturner** [comment]
Agreed. I will post a new PR, cancelling this one, with the updated microcode once it becomes available.

**Comment by rneilturner** [comment]
Last week Intel has pulled the updated microcode to mitigate against Spectre due to instabilities seems from OEM's. In addition, during our long term testing we have verified the microcode update causes major instabilities on Xen. One of our long term tests includes reboots across multiple VM's. With the microcode we were not able to achieve greater than 30 reboots for a single guest, eventually leading to the CPU completely locking. For these reasons I will be declining this PR until Intel releases a stable microcode update. Once Intel does make a release available, our test team with again verify the long term stability of the update.

**Pull request closed without merging**
