### PR TITLE
Linux 3.18.25 & latest XSAs

### PR DESCRIPTION
**Pull request by eric-ch**
Upgrade Linux 3.18 kernels to 3.18.25.

Add XSA-155, XSA-157, XSA-159, XSA-160, XSA-162, XSA-165 and XSA-166 to Xen, QEMU and Linux (3.18 and 4.1) patch-queues.

### CODE REVIEW

**Comment by transpute** [comment]
See https://openxt.atlassian.net/browse/OXT-457 for Qubes PV frontend fixes related to these XSAs, which may or may not apply to OpenXT guest VMs.

**Comment by jean-edouard** [comment]
Built (ext-344). Testing today.

**Comment by jean-edouard** [comment]
Ahem, sorry...
I'll try to test and merge this on Monday morning.
If there's any objection, please comment now.

**Comment by jean-edouard** [comment]
Working good, merging soon.

**Pull request merged**
