### PR TITLE
xen-blktap: install headers

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
LGTM. Does this go with a ticket?

**Comment by jean-edouard** [comment]
I'd say it falls under OXT-519.

**Comment by jean-edouard** [comment]
(This is needed for upcoming `xen-libxl.bb` recipe, that links against the blktap lib(s))

**Comment by rossphilipson** [comment]
Ack, merging soon.

**Pull request merged**
