### PR TITLE
OXT-1276: [Linux 4.14] Add Linux 4.14 support

### PR DESCRIPTION
**Pull request by rneilturner**
Signed-off-by: Richard Turner <turnerr@ainfosec.com>

See OXT-1276

This PR will add support to OpenXT for Linux Kernel LTS 4.14 within Dom0 and all Service VM's. I have based the below patches against the latest release of 4.14.22. I have opted to keep the older 4.9 LTS in case anyone prefers to have a stable kernel in their master build. To build against 4.9, just change your preferred kernel version within your local config. There are many improvements that have been made from 4.9 to 4.14 including initial CoffeeLake support and PVH Xen support to name a few. I have performed preliminary testing against both Dell and HP Haswell and SkyLake machines using both TPM 1.2 and 2.0. Additional testing will be performed in the coming weeks by my test team, to include CoffeeLake once UEFI is introduced. Any deficiencies will be reported if they apply to OpenXT. This PR will give the community an opportunity to perform parallel testing while the AIS test team begins theirs. Anyone looking at PVH support can use this PR to begin development.

Dependent PR's are as follows:

https://github.com/OpenXT/xenfb2/pull/5
https://github.com/OpenXT/fbtap/pull/2
https://github.com/OpenXT/v4v/pull/30
https://github.com/OpenXT/installer/pull/64

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [#1368](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1368)

**Comment by dpsmith** [comment]
I might suggestion picking up the following patch[[1](https://lkml.org/lkml/2018/2/28/289)] that Jason has submitted upstream. Upstream has already accepted, but may take a moment to trickle back down to us.

**Comment by jean-edouard** [comment]
@dpsmith very interesting patch indeed! I'd suggest PR-ing that separately though.

**Comment by jean-edouard** [comment]
@rneilturner, I tested the build mentioned above, which installed but didn't boot, because of missing SELinux rules. So I booted in permissive mode and got the following AVCs:
```
Mar  5 18:26:04.026295 kernel:[    2.617322] audit: type=1400 audit(1520274359.468:3): avc:  denied  { read } for  pid=116 comm="restorecon" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026296 kernel:[    2.617356] audit: type=1400 audit(1520274359.468:4): avc:  denied  { open } for  pid=116 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026297 kernel:[    2.693186] audit: type=1400 audit(1520274359.548:5): avc:  denied  { read } for  pid=126 comm="udevd" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026298 kernel:[    2.693222] audit: type=1400 audit(1520274359.548:6): avc:  denied  { open } for  pid=126 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026299 kernel:[    2.693254] audit: type=1400 audit(1520274359.548:7): avc:  denied  { getattr } for  pid=126 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026305 kernel:[    3.699132] audit: type=1400 audit(1520274360.548:8): avc:  denied  { accept } for  pid=174 comm="cryptsetup" scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:system_r:lvm_t:s0 tclass=socket permissive=1
Mar  5 18:26:04.026313 kernel:[    5.518064] audit: type=1400 audit(1520274361.279:12): avc:  denied  { read } for  pid=618 comm="dbus-daemon" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026314 kernel:[    5.518118] audit: type=1400 audit(1520274361.279:13): avc:  denied  { open } for  pid=618 comm="dbus-daemon" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026315 kernel:[    5.518154] audit: type=1400 audit(1520274361.279:14): avc:  denied  { getattr } for  pid=618 comm="dbus-daemon" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026316 kernel:[    5.528494] audit: type=1400 audit(1520274361.289:15): avc:  denied  { read } for  pid=622 comm="restorecon" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026317 kernel:[    5.528529] audit: type=1400 audit(1520274361.289:16): avc:  denied  { open } for  pid=622 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026381 kernel:[    5.539703] audit: type=1400 audit(1520274361.299:17): avc:  denied  { read } for  pid=623 comm="udevd" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026383 kernel:[    5.539733] audit: type=1400 audit(1520274361.299:18): avc:  denied  { open } for  pid=623 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026384 kernel:[    5.539760] audit: type=1400 audit(1520274361.299:19): avc:  denied  { getattr } for  pid=623 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026477 kernel:[    5.759898] audit: type=1400 audit(1520274361.529:20): avc:  denied  { read } for  pid=698 comm="restorecon" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026478 kernel:[    5.759936] audit: type=1400 audit(1520274361.529:21): avc:  denied  { open } for  pid=698 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026493 kernel:[    5.845328] audit: type=1400 audit(1520274361.609:22): avc:  denied  { read } for  pid=717 comm="lvmetad" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026494 kernel:[    5.845363] audit: type=1400 audit(1520274361.609:23): avc:  denied  { open } for  pid=717 comm="lvmetad" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.026515 kernel:[    5.845396] audit: type=1400 audit(1520274361.609:24): avc:  denied  { getattr } for  pid=717 comm="lvmetad" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.475433 kernel:[    8.847480] audit: type=1400 audit(1520274364.459:25): avc:  denied  { read } for  pid=843 comm="udevadm" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.475443 kernel:[    8.847517] audit: type=1400 audit(1520274364.459:26): avc:  denied  { open } for  pid=843 comm="udevadm" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.475445 kernel:[    8.847566] audit: type=1400 audit(1520274364.459:27): avc:  denied  { getattr } for  pid=843 comm="udevadm" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.715321 kernel:[    9.087733] audit: type=1400 audit(1520274364.699:28): avc:  denied  { read } for  pid=922 comm="restorecon" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.715337 kernel:[    9.087770] audit: type=1400 audit(1520274364.699:29): avc:  denied  { open } for  pid=922 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.755478 kernel:[    9.129480] audit: type=1400 audit(1520274364.739:30): avc:  denied  { read } for  pid=932 comm="restorecon" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:04.755495 kernel:[    9.129511] audit: type=1400 audit(1520274364.739:31): avc:  denied  { open } for  pid=932 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:34.375302 kernel:[   38.742353] audit: type=1400 audit(1520274394.359:32): avc:  denied  { read } for  pid=1532 comm="sshd" name="config" dev="dm-3" ino=22530 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:34.375322 kernel:[   38.742406] audit: type=1400 audit(1520274394.359:33): avc:  denied  { open } for  pid=1532 comm="sshd" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:34.375324 kernel:[   38.742434] audit: type=1400 audit(1520274394.359:34): avc:  denied  { getattr } for  pid=1532 comm="sshd" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:35.435295 kernel:[   39.803697] audit: type=1400 audit(1520274395.419:35): avc:  denied  { read } for  pid=1549 comm="newrole" name="config" dev="dm-3" ino=22530 scontext=root:staff_r:newrole_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:35.435307 kernel:[   39.803745] audit: type=1400 audit(1520274395.419:36): avc:  denied  { open } for  pid=1549 comm="newrole" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=root:staff_r:newrole_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar  5 18:26:35.435308 kernel:[   39.803774] audit: type=1400 audit(1520274395.419:37): avc:  denied  { getattr } for  pid=1549 comm="newrole" path="/etc/selinux/config" dev="dm-3" ino=22530 scontext=root:staff_r:newrole_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
```

**Comment by eric-ch** [comment]
Installation will hang asking for administrative passphrase on the serial for me as well (Dell E7450). SELinux seems to be the culprit:
```
[    2.327865] SELinux:  Permission validate_trans in class security not defined in policy.
[    2.327894] SELinux:  Permission getrlimit in class process not defined in policy.
[    2.327901] SELinux:  Class process2 not defined in policy.
[    2.327906] SELinux:  Permission module_load in class system not defined in policy.
[    2.327920] SELinux:  Permission map in class file not defined in policy.
[    2.327928] SELinux:  Permission map in class dir not defined in policy.
[    2.327936] SELinux:  Permission map in class lnk_file not defined in policy.
[    2.327944] SELinux:  Permission map in class chr_file not defined in policy.
[    2.327952] SELinux:  Permission map in class blk_file not defined in policy.
[    2.327960] SELinux:  Permission map in class sock_file not defined in policy.
[    2.327968] SELinux:  Permission map in class fifo_file not defined in policy.
[    2.327976] SELinux:  Permission map in class socket not defined in policy.
```

Is there another PR for the SELinux policy?

**Comment by rneilturner** [comment]
That is interesting, I didn't get any hangs. Are you installing with measured launch? I usually don't try running with non-MLE.

**Comment by jean-edouard** [comment]
@rneilturner yup, non-MLE.

**Comment by rneilturner** [comment]
Ok, I will give it a go with non-MLE, probably running into the same issue. I will deep dive into the SELinux denials and get them posted soon.

**Comment by eric-ch** [comment]
@rneilturner from the second log, it seems maybe the refpolicy-mcs 2014 is a little outdated. I have ported the patch-queue on the 2017 for pyro if that can help.
For example, the 2017 has:
```
policy/flask/access_vectors:436:        validate_trans
```
Which is not in the 2014 that is shipped with Jethro.

**Comment by rneilturner** [comment]
It seems @stephensmalley has solved these SELinux issues upstream: https://android-review.googlesource.com/c/platform/system/sepolicy/+/432339 and https://lkml.org/lkml/2017/7/10/329 for android systems. I will continue to investigate.

**Comment by stephensmalley** [comment]
Not sure I follow.  The denials posted above by jed weren't for map or validate_trans; they were denials due to /etc/selinux/config being unlabeled.  Probably something during install manually created /etc/selinux/config w/ SELinux disabled or before policy was loaded and didn't set a context on it?  Might be as easy as doing a restorecon /etc/selinux/config.
WRT map permission if it is actually causing you denials, you have a few options:
1) Allow unknown permissions (this is what Fedora does to avoid breakage on new kernels with new permission checks with old policy).  Controlled by UNK_PERMS in build.conf or make command line for refpolicy, meta-selinux defines a POLICY_UNK_PERMS in refpolicy_common.inc, defaults to allow, not sure what it is in OpenXT.  seinfo /path/to/policy will report it on the Handle unknown classes line.
2) Take the approach used in my original submission for refpolicy of allowing map whenever open was allowed, http://oss.tresys.com/pipermail/refpolicy/2017-May/009534.html. Rejected upstream because they wanted to only allow map where truly needed,
3) Try to pull in all of the upstream refpolicy commits relating to map permission (lots of them, starting from my commit 7a4e93a385ff186c6dc8c5b36bdd4461eec251c3).

**Comment by eric-ch** [comment]
@stephensmalley My apologies, I was referring to the first line of kernel log I posted earlier, which is likely not related to the denials @jean-edouard mentioned.

**Comment by stephensmalley** [comment]
Yes, those are warnings but they aren't necessarily a problem unless your policy is set to deny unknown permissions, which the next line of the log would have shown, ala:
 SELinux: the above unknown classes and permissions will be denied
In Fedora/RHEL, policy is configured to allow unknown permissions to provide forward kernel compatibility.  In Android, policy is configured to deny unknown permissions because kernels and policy are always updated together and it is the stricter configuration.

**Comment by jandryuk** [comment]
patches/xenstore-no-read-vs-write-atomicity.patch can be dropped; it's functionality is already included - upstream commit 581d21a2d02a798ee34e56dbfa13f891b3a90c30 ("xenbus: fix deadlock on writes to /proc/xen/xenbus")

**Comment by rneilturner** [comment]
Thank you @jandryuk I added a commit to remove the patch. @jean-edouard I added another PR to the installer repo to fix the SELinux denial to fix the /etc/selinux/config context. @eric-ch the problem with the permissions you have seen should be resolved with the update to Pyro. As of right now this should be good for review and a build to test.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1395

Got one seemingly harmless AVC on a measured install, pretty sure that can be allowed:
```
Mar 14 17:11:16.115676 kernel:[  427.316307] audit: type=1400 audit(1521047476.099:50): avc:  denied  { dac_read_search } for  pid=3047 comm="tapdisk" capability=2  scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tclass=capability permissive=0
```
However, un-measured installs still fail to boot in enforcing mode, with the following AVCs:
```
Mar 14 17:20:35.026718 kernel:[    2.607358] audit: type=1400 audit(1521048030.452:3): avc:  denied  { read } for  pid=116 comm="restorecon" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026719 kernel:[    2.607393] audit: type=1400 audit(1521048030.452:4): avc:  denied  { open } for  pid=116 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026720 kernel:[    2.683481] audit: type=1400 audit(1521048030.532:5): avc:  denied  { read } for  pid=126 comm="udevd" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026721 kernel:[    2.683518] audit: type=1400 audit(1521048030.532:6): avc:  denied  { open } for  pid=126 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026722 kernel:[    2.683610] audit: type=1400 audit(1521048030.532:7): avc:  denied  { getattr } for  pid=126 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026727 kernel:[    3.577875] audit: type=1400 audit(1521048031.422:8): avc:  denied  { accept } for  pid=174 comm="cryptsetup" scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:system_r:lvm_t:s0 tclass=socket permissive=1
Mar 14 17:20:35.026762 kernel:[    5.398010] audit: type=1400 audit(1521048032.279:12): avc:  denied  { read } for  pid=618 comm="dbus-daemon" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026763 kernel:[    5.398064] audit: type=1400 audit(1521048032.279:13): avc:  denied  { open } for  pid=618 comm="dbus-daemon" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026764 kernel:[    5.398099] audit: type=1400 audit(1521048032.279:14): avc:  denied  { getattr } for  pid=618 comm="dbus-daemon" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026765 kernel:[    5.408200] audit: type=1400 audit(1521048032.289:15): avc:  denied  { read } for  pid=622 comm="restorecon" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026766 kernel:[    5.408236] audit: type=1400 audit(1521048032.289:16): avc:  denied  { open } for  pid=622 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026830 kernel:[    5.419462] audit: type=1400 audit(1521048032.299:17): avc:  denied  { read } for  pid=623 comm="udevd" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026837 kernel:[    5.419493] audit: type=1400 audit(1521048032.299:18): avc:  denied  { open } for  pid=623 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026838 kernel:[    5.419519] audit: type=1400 audit(1521048032.299:19): avc:  denied  { getattr } for  pid=623 comm="udevd" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026864 kernel:[    5.588191] audit: type=1400 audit(1521048032.469:20): avc:  denied  { read } for  pid=664 comm="restorecon" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026865 kernel:[    5.588229] audit: type=1400 audit(1521048032.469:21): avc:  denied  { open } for  pid=664 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026877 kernel:[    5.714482] audit: type=1400 audit(1521048032.599:22): avc:  denied  { read } for  pid=694 comm="lvmetad" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026878 kernel:[    5.714512] audit: type=1400 audit(1521048032.599:23): avc:  denied  { open } for  pid=694 comm="lvmetad" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.026879 kernel:[    5.714538] audit: type=1400 audit(1521048032.599:24): avc:  denied  { getattr } for  pid=694 comm="lvmetad" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.485454 kernel:[    8.135191] audit: type=1400 audit(1521048035.469:25): avc:  denied  { read } for  pid=823 comm="udevadm" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.485466 kernel:[    8.135221] audit: type=1400 audit(1521048035.469:26): avc:  denied  { open } for  pid=823 comm="udevadm" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.485468 kernel:[    8.135271] audit: type=1400 audit(1521048035.469:27): avc:  denied  { getattr } for  pid=823 comm="udevadm" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.715341 kernel:[    8.367715] audit: type=1400 audit(1521048035.699:28): avc:  denied  { read } for  pid=902 comm="restorecon" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.715361 kernel:[    8.367752] audit: type=1400 audit(1521048035.699:29): avc:  denied  { open } for  pid=902 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.745341 kernel:[    8.393672] audit: type=1400 audit(1521048035.729:30): avc:  denied  { read } for  pid=908 comm="restorecon" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:35.745357 kernel:[    8.393709] audit: type=1400 audit(1521048035.729:31): avc:  denied  { open } for  pid=908 comm="restorecon" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:setfiles_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:36.045342 kernel:[    8.695565] audit: type=1400 audit(1521048036.029:32): avc:  denied  { dac_read_search } for  pid=942 comm="tapdisk" capability=2  scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tclass=capability permissive=1
Mar 14 17:20:37.295427 kernel:[    9.940734] audit: type=1400 audit(1521048037.279:33): avc:  denied  { dac_read_search } for  pid=951 comm="tapdisk" capability=2  scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tclass=capability permissive=1
Mar 14 17:20:38.715365 kernel:[   11.364645] audit: type=1400 audit(1521048038.699:34): avc:  denied  { read } for  pid=929 comm="login" name="config" dev="dm-3" ino=32130 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:38.715376 kernel:[   11.364702] audit: type=1400 audit(1521048038.699:35): avc:  denied  { open } for  pid=929 comm="login" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:38.715377 kernel:[   11.364737] audit: type=1400 audit(1521048038.699:36): avc:  denied  { getattr } for  pid=929 comm="login" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:41.345339 kernel:[   13.998280] audit: type=1400 audit(1521048041.329:37): avc:  denied  { read } for  pid=1066 comm="newrole" name="config" dev="dm-3" ino=32130 scontext=root:sysadm_r:newrole_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:41.345354 kernel:[   13.998335] audit: type=1400 audit(1521048041.329:38): avc:  denied  { open } for  pid=1066 comm="newrole" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=root:sysadm_r:newrole_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:41.345356 kernel:[   13.998370] audit: type=1400 audit(1521048041.329:39): avc:  denied  { getattr } for  pid=1066 comm="newrole" path="/etc/selinux/config" dev="dm-3" ino=32130 scontext=root:sysadm_r:newrole_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 14 17:20:43.385337 kernel:[   16.030066] audit: type=1400 audit(1521048043.359:40): avc:  denied  { dac_read_search } for  pid=1082 comm="tapdisk" capability=2  scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tclass=capability permissive=1
```

**Comment by eric-ch** [comment]
Merging soon.

**Pull request merged**
