### PR TITLE
Master fix clean targets

### PR DESCRIPTION
**Pull request by cjp256**

### CODE REVIEW

**Comment by jean-edouard** [comment]
Can you please provide more details about what this is doing? Thanks

**Comment by aikidokatech** [comment]
I believe this is to fix the fact that at least three recipes file if attempting to build a second time without an explicit clean.  Examples are xenfb2 and v4v-module.  Being that development traditionally was always done with a builder that uses a fresh tree, it was never fixed before.

**Comment by cjp256** [comment]
aikidokatech is right.

if fixes clean steps, which I have hit doing jethro-based work.

**Comment by cjp256** [comment]
ping! :)

**Comment by jean-edouard** [comment]
I still don't get it, but @aikidokatech seems to +1, I'll merge soon.

**Pull request merged**
