### PR TITLE
tpm-scripts: fix tpm_get_pcr grep format

### PR DESCRIPTION
**Pull request by eric-ch**
For TPM1.2, /sys/class/tpm/tpm0/pcrs is [formatted with](https://elixir.bootlin.com/linux/v5.4.131/source/drivers/char/tpm/tpm-sysfs.c#L118): 'PCR-%02d: %02X %02X...'
The use of grep does not account for the 0 padding for PCRs below 10, which breaks forward seal on UEFI/TPM1.2 systems. The bug is mostly silent (apart from failing to unseal after upgrading/forward-sealing):
- tpm_get_pcr returns an empty string for PCR 8
- `! contains_only "$pcr8" "0"` is used to detect a UEFI measured   installation. `contains_only` will return true for   an empty-string given for the PCR value, for any character value.
- In turn, `seal-system` calls `calculate_drtm_pcr` for legacy installations, using `/boot/system/grub/grub.cfg` and setting SRTM to 0.

This leads to PCR18 and PCR19 not being predicted correctly, but predicted nonetheless while no error is apparently raised when performing the upgrade/forward-seal.

### CODE REVIEW

**Comment by jandryuk** [comment]
Would you please expand the commit message with something like:
Currently, forward seal on a UEFI/TPM1.2 system is broken.  The check for PCR-8 returns an empty string, which matches in contains_only 0.  That in turn causes calculate_drtm_pcrs to use the legacy grub.cfg instead of openxt.cfg leading to an incorrect PCR-19.  With this change, forward seal is against grub.cfg.

You can use that verbatim if you like.

**Review by jandryuk — APPROVED** [review]
Code LGTM

**Comment by eric-ch** [comment]
@jandryuk Yes of course, the commit message is too succinct. Also, I wanted to fix the false-positive in `contains_only`, but did not push it.

**Review by jandryuk — APPROVED** [review]
LGTM.  Thanks.

**Comment by jandryuk** [comment]
Will merge soon.

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/22/builds/44): [$master-custom-44](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom/44/)

**Pull request merged**
