### PR TITLE
layer/master: per sub-project srcrev

### PR DESCRIPTION
**Pull request by eric-ch**
Master is intended to track the tip of OpenXT layers and subproject, forward port the reorganization done for zeus to define each subproject SRCREV for each repository involved by each recipe.

In order to simplify version management, since multiple recipes can pull a common repository, move the source/revision configuration to a matching include file and sort the recipes per repository provider.

(cherry picked from commit 72ea9fc8a552042ea45c1cd535fb142df91de94c)

This change will break existing build-systems that rely on `OPENXT_GIT_MIRROR`, `OPENXT_GIT_PROTOCOL`, and `OPENXT_BRANCH` configuration variables that were used until now. Following are a couple of suggestion on how one can avoid that pain:

#### For development trees

You no longer need local clones of sub-projects laid out in a pre-defined way to build OpenXT. The layer now points to the upstream repositories directly. OE will fetch them for you, then you can work in-tree, or better use Yocto [devtool](https://www.yoctoproject.org/software-item/devtool/) utility to work in a local clone of the repository used by the recipe of the project you want to modify.
Build scripts (e.g, [bordel](https://github.com/apertussolutions/bordel)) are still required as the OpenXT layer is not able to produce a bootable installer image or an OTA upgrade repository staging for OpenXT at this time.

#### For automated builders

It is likely one might want to build a specific revision of an OpenXT sub-project (e.g, test a change in https://github.com/OpenXT/manager only). There is more than one way to do this and it depends on how your builder is configured. One possibility is to use [externalsrc](https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#ref-classes-externalsrc) to build a local clone of said repository pointing to the revision you wish to test. As an example, add https://github.com/eric-ch/meta-openxt-externalsrc to your layers will achieve that by building *all* OpenXT subprojects against a local clone of their repositories (you will need to clone *all* of them).

### CODE REVIEW

**Review by jandryuk — APPROVED** [review]

**Comment by jandryuk** [comment]
Will merge soon.

**Comment by eric-ch** [comment]
The [Build](openxt.ainfosec.com/buildbot/#/builders/11/builds/1/steps/14) failed, please hold.

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/11/builds/2): [$master-stable-2](https://openxt.ainfosec.com/OpenXT/auto/master/master-stable/2/)

**Comment by jandryuk** [comment]
Will here soon.

**Comment by eric-ch** [comment]
v3: rebase branch (conflict).

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/11/builds/4): [$master-stable-4](https://openxt.ainfosec.com/OpenXT/auto/master/master-stable/4/)

**Pull request merged**
