### PR TITLE
[tpm2.0] Take ownership of lockout hierarchy

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1148

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/954

**Comment by jean-edouard** [comment]
@crogers1, @dpsmith, should this be PR-ed against stable-7?

**Comment by dpsmith** [comment]
Yes, because hopefully in RC2 we will have the password capture fix.

**Comment by eric-ch** [comment]
Build [978](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/978)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1012

**Comment by jean-edouard** [comment]
Merging tomorrow.

**Comment by dpsmith** [comment]
Am I missing it or has there not been a stable-7 version?

**Comment by crogers1** [comment]
I must've forgotten, I'll push that now.

**Comment by dpsmith** [comment]
No worries, was looking to close out JIRA issues.

**Pull request merged**
