### PR TITLE
Uprev to Linux 6.1.33

### PR DESCRIPTION
**Pull request by crogers1**
Recipe and patch changes to uprev dom0 and servicevm linux versions to the 6.1 LTS.

There is one other accompanying PR against linux-xen-argo here: https://github.com/OpenXT/linux-xen-argo/pull/19

### CODE REVIEW

**Comment by crogers1** [comment]
Opened a new PR due to Github issues

**Comment by jandryuk** [comment]
I think we want an update of `conf/distro/openxt-main.conf`:
```
WARNING: preferred version 5.15% of linux-openxt not available (for item virtual/kernel)
WARNING: versions of linux-openxt available: 6.1.24
```

Though maybe that can be dropped since we only have a single version of linux-openxt?

**Comment by crogers1** [comment]
I can update that.  I'd leave it in, in case we look to support multiple kernel versions again.

**Comment by crogers1** [comment]
Dependent PRs:
https://github.com/OpenXT/linux-xen-argo/pull/19
https://gitlab.com/vglass/openxtfb/-/merge_requests/5

**Comment by jandryuk** [comment]
6.1.33 is available with the revert-mtrr.patch included.  Dom0 booted with 6.1.33 for me - though I don't know if this machine was affected by the ioremap issue.

**Comment by crogers1** [comment]
Updated the recipe to build 6.1.33 and dropped the revert-mtrr.patch since they merged it into this micro uprev

**Comment by crogers1** [comment]
linux-libc-headers warning resolved.

**Comment by crogers1** [comment]
Patch to `audit` applied in new commit, takes the `%immutable` approach you recommended.

**Pull request merged**
