### PR TITLE
[udev] use pci.ids and usb.ids for providing complete device information

### PR DESCRIPTION
**Pull request by jean-edouard**
Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
"...once xenmgr is patched to use the non-gzipped file"

Maybe we should fix it here?

**Comment by jean-edouard** [comment]
This pull request is basically adding the uncompressed version of pci.ids. It doesn't remove the compressed one because xenmgr depends on it.
Xenmgr, and everything else that uses the compressed version, should be modified to use the uncompressed one, so that we can remove the compressed file and save 200KB of disk space for the dom0 rootfs.
This pull request can stay open until xenmgr, and potential others, are ready to use the uncompressed file.

**Comment by jean-edouard** [comment]
PR submitted against xenmgr to use the uncompressed file and added a commit to get rid of the compressed one.
Please merge at the same time as https://github.com/OpenXT/manager/pull/11

**Comment by rossphilipson** [comment]
Just tested, +1, merging

**Pull request merged**
