### PR TITLE
Upgrade linux-firmware

### PR DESCRIPTION
**Pull request by eric-ch**
Move to linux-firmware top revision.

### CODE REVIEW

**Comment by rossphilipson** [comment]
See my comment here: https://github.com/OpenXT/xenclient-oe/pull/140

I think we should just get this in too.

**Comment by jean-edouard** [comment]
+1 too.
This is a requirement for Broadwell support, heavily tested upstream and unpatchable anyway.

**Comment by jean-edouard** [comment]
Will merge soon.

**Comment by pearsonk** [comment]
I agree with @rossphilipson and @jean-edouard, makes sense to merge these ASAP to we can test it all together

**Pull request merged**
