### PR TITLE
OXT-1081: logrotate: replace fedorahosted.org SRC_URI with github.com

### PR DESCRIPTION
**Pull request by eric-ch**
From: Choong YinThong
Date: Sun, 9 Apr 2017 16:33:18 -0700
Subject: [PATCH] logrotate: replace fedorahosted.org SRC_URI with github.com
 source

fedorahosted.org was retired on March 1st, 2017. This is to
update the SRC_URI to point to github.com.
Update the ${PN} to ${BPN} in order to pass the autobuilder
mulitlib enable configuration.

[YOCTO #11226]
OXT-1081

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [800](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/800).

**Comment by eric-ch** [comment]
This is duplicating upstream recipe to keep the build working until submission in upstream jethro branch.

**Comment by jean-edouard** [comment]
Builds boots LGTM +1

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
