### PR TITLE
OXT-1531: 4.19.32 micro-upgrade and defconfig cleanup

### PR DESCRIPTION
**Pull request by eric-ch**
Before reading: This is rebased on https://github.com/OpenXT/xenclient-oe/pull/1113 to account for changes in the `txt` module.

Dom0 kernel used to be deployed in the installer, requiring network drivers that are not desirable dom0 once deployed and were removed at image creation.

Installer and Dom0 no longer share a kernel, so the drivers in question can be removed from the configuration.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6476

**Comment by eric-ch** [comment]
v2:
- Rebase on master+https://github.com/OpenXT/xenclient-oe/pull/1113

**Comment by eric-ch** [comment]
v3:
- Rebased on master
- Trim installer configuration: `CONFIG_XEN_BALLOON`, `CONFIG_XEN_BACKEND` and `CONFIG_XEN_FBDEV2_FRONTEND`.
- Dom0 add `CONFIG_XEN_SCRUB_PAGES_DEFAULT` since the BALLOON driver is available.
- blktap2: discard_zeroes_data field disappeared in `48920ff2a5a9 block: remove the discard_zeroes_data flag`, so remove the flag tied to it.
- thorough-reset-interface-to-pciback-s-sysfs.patch: Remove unused functions
- xenbus-move-otherend-watches-on-relocate.patch: Use type expected by kasprintf format with limit.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6479

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
