### PR TITLE
STABLE-8: OXT-1421: XSA-270 Linux netback driver OOB access in hash handling 

### PR DESCRIPTION
**Pull request by jandryuk**
https://xenbits.xen.org/xsa/advisory-270.html

This is not upstream yet.

OXT-1421

This is on top of https://github.com/OpenXT/xenclient-oe/pull/1032. Once that is merged, it is just a single commit.

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [$1710](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1710)

**Comment by eric-ch** [comment]
With https://github.com/OpenXT/xenclient-oe/pull/1032 merged, this one can be rebased as well. Sorry for the inconvenience.

**Comment by jandryuk** [comment]
Done.  Leaving an open PR served as a reminder.

**Comment by eric-ch** [comment]
Build [$1719](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1719)

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
