### PR TITLE
XSA-155 Qubes OS frontend fixes for LInux 4.1

### PR DESCRIPTION
**Pull request by eric-ch**
Qubes Security Bulleting #23:
https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-023-2015.txt
Original patches:
https://github.com/QubesOS/qubes-linux-kernel/tree/stable-3.18/patches.xen

OXT-461

Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
@eric-ch what is the reason for using the QubesOS version of the patches instead of the "official" ones? (http://xenbits.xen.org/xsa/advisory-155.html)

**Comment by richpersaud** [comment]
See the driver domain discussion in the Qubes bulletin and JIRA ticket.

"The significance of frontend bugs for Qubes OS: It's worth stressing that the Xen Security Team decided to consider only bugs in the backends as security-critical."

**Comment by eric-ch** [comment]
QubesOS patches are not part of XSA-155 released patches.
As @richpersaud said, XSA-155 only address backends, QubesOS fixes address the issue when the frontend runs in a trusted domain.

**Comment by jean-edouard** [comment]
Got it, thank you, I'll test this.

**Comment by jean-edouard** [comment]
Built there: http://openxt.ainfosec.com:81/builds/master/ext-dev-355-master/
LGTM, will merge soon.
It is also probably a good candidate for stable-5, since it seems to be a pretty critical security issue.

**Comment by eric-ch** [comment]
My apologies, the PR was not what I meant to push (hence the rebase), it was missing the recipe (so patches were not applied...) and 2 ported patches for 4.1 (so they would not apply anyway)...
@jean-edouard can we start another build to be sure I did not commit more muppetry please?

**Comment by jean-edouard** [comment]
Yup http://openxt.ainfosec.com:8020/builders/extbuilder/builds/360

**Comment by jean-edouard** [comment]
Builds and boots fine, including VMs, will merge soon.

**Pull request merged**
