### PR TITLE
refpolicy: split policy for rpc-proxy vs dbusbouncer

### PR DESCRIPTION
**Pull request by stephensmalley**
rpc-proxy and dbusbouncer are two different programs, one of which runs in dom0 and the other in the ndvm, and they have different interactions with other processes in the system, but they were running in the same domain, dbusbouncer_t.  Split rpc-proxy into its own rpcproxy_t domain and specialize both domains to only allow what is required for each program.  Delete legacy types and rules that are not in use in OpenXT.

OXT-799

### CODE REVIEW

**Comment by eric-ch** [comment]
Network-daemon has some issue with this:
```
Nov  1 15:55:52.583595 xenconsoled: Network (1): [    1.955339] audit: type=1400 audit(1478015752.568:4): avc:  denied  { getattr } for  pid=608 comm="dbusbou
ncer" path="/dev/xen/xenbus" dev="devtmpfs" ino=7997 scontext=system_u:system_r:dbusbouncer_t:s0 tcontext=system_u:object_r:xen_device_t:s0 tclass=chr_file pe
rmissive=0
Nov  1 15:55:52.588369 xenconsoled: Network (1): kernel: [    1.955339] audit: type=1400 audit(1478015752.568:4): avc:  denied  { getattr } for  pid=608 comm=
"dbusbouncer" path="/dev/xen/xenbus" dev="devtmpfs" ino=7997 scontext=system_u:system_r:dbusbouncer_t:s0 tcontext=system_u:object_r:xen_device_t:s0 tclass=chr
_file permissive=0
Nov  1 15:56:02.616793 dbus[720]: avc:  denied  { send_msg } for msgtype=method_call interface=org.freedesktop.DBus.Introspectable member=Introspect dest=com.
citrix.xenclient.networkdaemon spid=915 tpid=905 scontext=system_u:system_r:rpcproxy_t:s0 tcontext=system_u:system_r:network_daemon_t:s0 tclass=dbus
Nov  1 15:56:02.620236 dbus[720]: avc:  denied  { send_msg } for msgtype=method_call interface=com.citrix.xenclient.networkdaemon member=list_backends dest=co
m.citrix.xenclient.networkdaemon spid=915 tpid=905 scontext=system_u:system_r:rpcproxy_t:s0 tcontext=system_u:system_r:network_daemon_t:s0 tclass=dbus
```

**Comment by stephensmalley** [comment]
Hmmm...I didn't see these in my testing.  How did you trigger them?

**Comment by eric-ch** [comment]
Fresh install + boot.
I will make sure I had everything fetched correctly.

**Comment by stephensmalley** [comment]
Those permissions are allowed by the policies in my build tree:
$ sesearch -A -s dbusbouncer_t -t xen_device_t -c chr_file build/tmp-glibc/work/xenclient_ndvm-oe-linux/xenclient-ndvm-image/1.0-r0/rootfs/etc/selinux/xc_policy/policy/policy.28
Found 1 semantic av rules:
   allow dbusbouncer_t xen_device_t : chr_file { ioctl read write getattr lock append open } ; 
$ sesearch -A -s rpcproxy_t -t network_daemon_t -c dbus build/tmp-glibc/work/xenclient_dom0-oe-linux/xenclient-dom0-image/1.0-r0/rootfs/etc/selinux/xc_policy/policy/policy.28
Found 1 semantic av rules:
   allow rpcproxy_t network_daemon_t : dbus send_msg ;

**Comment by eric-ch** [comment]
Installing custom-build 201 (which includes this PR) does not present the defect I was seeing with my build.

**Comment by stephensmalley** [comment]
Ok.  I do recall encountering a similar problem while testing the first commit earlier, but cleaning my refpolicy-mcs and rebuilding again seemed to fix it.

**Comment by eric-ch** [comment]
LGTM.

**Pull request merged**
