### PR TITLE
selinux: fix blktap-related AVCs

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1430

**Comment by eric-ch** [comment]
Building [$1435](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1435)

**Comment by eric-ch** [comment]
From last build logs:
```
Mar 29 19:15:59.020937 kernel:[    6.779493] audit: type=1400 audit(1522350957.150:4): avc:  denied  { create } for  pid=759 comm="tap-ctl" name="blktap0" scontext=system_u:system_r:tapctl_t:s0 tcontext=system_u:object_r:blktap_device_t:s0:c0 tclass=chr_file permissive=0
Mar 29 19:15:59.020938 kernel:[    6.785368] audit: type=1400 audit(1522350957.160:5): avc:  denied  { create } for  pid=762 comm="tap-ctl" name="blktap0" scontext=system_u:system_r:tapctl_t:s0 tcontext=system_u:object_r:blktap_device_t:s0:c0 tclass=chr_file permissive=0
Mar 29 19:15:59.020938 kernel:[    6.790886] audit: type=1400 audit(1522350957.170:6): avc:  denied  { create } for  pid=765 comm="tap-ctl" name="blktap0" scontext=system_u:system_r:tapctl_t:s0 tcontext=system_u:object_r:blktap_device_t:s0:c0 tclass=chr_file permissive=0
```

But VMs are up and happy...

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1441

**Comment by eric-ch** [comment]
With build [$1441](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1441), right after booting:
```
Apr  2 20:27:26.022949 kernel:[   18.222397] audit: type=1400 audit(1522700844.170:4): avc:  denied  { create } for  pid=750 comm="tap-ctl" name="blktap0" scontext=system_u:system_r:tapctl_t:s0 tcontext=system_u:object_r:blktap_device_t:s0:c0 tclass=chr_file permissive=0
Apr  2 20:27:26.022950 kernel:[   18.228600] audit: type=1400 audit(1522700844.170:5): avc:  denied  { create } for  pid=753 comm="tap-ctl" name="blktap0" scontext=system_u:system_r:tapctl_t:s0 tcontext=system_u:object_r:blktap_device_t:s0:c0 tclass=chr_file permissive=0
Apr  2 20:27:26.022951 kernel:[   18.234838] audit: type=1400 audit(1522700844.180:6): avc:  denied  { create } for  pid=756 comm="tap-ctl" name="blktap0" scontext=system_u:system_r:tapctl_t:s0 tcontext=system_u:object_r:blktap_device_t:s0:c0 tclass=chr_file permissive=0
Apr  2 20:27:27.508147 kernel:[   21.370350] audit: type=1400 audit(1522700847.500:7): avc:  denied  { search } for  pid=1042 comm="input_server" name="udev" dev="tmpfs" ino=12473 scontext=system_u:system_r:input_server_t:s0 tcontext=system_u:object_r:udev_var_run_t:s0 tclass=dir permissive=0
Apr  2 20:27:36.977604 kernel:[   30.832057] audit: type=1400 audit(1522700856.960:8): avc:  denied  { use } for  pid=1150 comm="tapdisk" path="/dev/null" dev="devtmpfs" ino=1029 scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:initrc_t:s0 tclass=fd permissive=0
Apr  2 20:27:36.987617 kernel:[   30.847253] audit: type=1400 audit(1522700856.970:9): avc:  denied  { use } for  pid=1155 comm="tapdisk" path="/dev/null" dev="devtmpfs" ino=1029 scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:initrc_t:s0 tclass=fd permissive=0
Apr  2 20:27:41.812672 xenconsoled: Network (1): [    3.718585] audit: type=1400 audit(1522700861.707:4): avc:  denied  { read } for  pid=609 comm="modprobe" path="/run/xtables.lock" dev="tmpfs" ino=10497 scontext=system_u:system_r:kmod_t:s0 tcontext=system_u:object_r:iptables_var_run_t:s0 tclass=file permissive=0
Apr  2 20:27:41.814214 xenconsoled: Network (1): kernel: [    3.718585] audit: type=1400 audit(1522700861.707:4): avc:  denied  { read } for  pid=609 comm="modprobe" path="/run/xtables.lock" dev="tmpfs" ino=10497 scontext=system_u:system_r:kmod_t:s0 tcontext=system_u:object_r:iptables_var_run_t:s0 tclass=file permissive=0
Apr  2 20:27:52.617630 kernel:[   46.478024] audit: type=1400 audit(1522700872.600:10): avc:  denied  { use } for  pid=1331 comm="tapdisk" path="/dev/null" dev="devtmpfs" ino=1029 scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:initrc_t:s0 tclass=fd permissive=0
Apr  2 20:27:52.637599 kernel:[   46.494524] audit: type=1400 audit(1522700872.620:11): avc:  denied  { use } for  pid=1340 comm="tapdisk" path="/dev/null" dev="devtmpfs" ino=1029 scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:initrc_t:s0 tclass=fd permissive=0
Apr  2 20:27:52.657601 kernel:[   46.519308] audit: type=1400 audit(1522700872.640:12): avc:  denied  { use } for  pid=1358 comm="tapdisk" path="/dev/null" dev="devtmpfs" ino=1029 scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:initrc_t:s0 tclass=fd permissive=0
```

Things are running fine though.

**Comment by eric-ch** [comment]
@jean-edouard Am I right assuming https://github.com/OpenXT/xenclient-oe/pull/856 makes this changeset obsolete?

**Comment by jean-edouard** [comment]
I... think so...

**Pull request closed without merging**
