### PR TITLE
ioemu: fix patch naming for hda audio recording

### PR DESCRIPTION
**Pull request by bennettj1087**
Patch file not ending in .patch was not being applied.

### CODE REVIEW

**Comment by jean-edouard** [comment]
My bad... Thanks for the fix!

**Comment by bennettj1087** [comment]
Sorry for the sucky commit message. :) @cjp256 is upset with me. :(

**Comment by jean-edouard** [comment]
Your commit message is nice, short and clear. The form of commit messages is free. We do have some *guidelines*, but they shouldn't be mistaken for compulsory rules. ;)

**Comment by cjp256** [comment]
Specifically, the lack of the sign-off (and the OXT-###)!

**Pull request merged**
