### PR TITLE
linux: remove modules selected by default during upgrades

### PR DESCRIPTION
**Pull request by eric-ch**
`CONFIG_XEN_PCIDEV_BACKEND` ended up in stubdomain and NDVM. Additionally some crypto modules (`CONFIG_CRYPTO_ECHAINIV`, `CONFIG_CRYPTO_DRBG`) were built as module and pulled in dependencies.

Given this went unnoticed, regenerate the kernel configurations using bitbake's `savedefconfig`. This removes the default and automatically selected statements, which should make review easier in the future.

### CODE REVIEW

**Review by jandryuk — APPROVED** [review]

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/22/builds/20): [master-custom-20](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom/20/)

**Review by jandryuk — APPROVED** [review]

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/22/builds/30): [$master-custom-30](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom/30/)

**Comment by eric-ch** [comment]
#### V2:

- Rebased on master post vGlass merge.

**Review by jandryuk — APPROVED** [review]
Looks like it was this build: https://openxt.ainfosec.com/buildbot/#/builders/22/builds/32

Will merge soon.

**Comment by eric-ch** [comment]
Indeed:
[Build](https://openxt.ainfosec.com/buildbot/#/builders/22/builds/32): [$master-custom-32](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom/32/)

**Pull request merged**
