### PR TITLE
[tpm2.0] Only support single bank sealing sha256

### PR DESCRIPTION
**Pull request by crogers1**
for now.

  OXT-1132

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Building here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/913

**Comment by rossphilipson** [comment]
Restarted here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/916

**Comment by rossphilipson** [comment]
Reviewed code, LGTM. Looks like it is correctly removing the sha1 parts for TPM2.0.

**Comment by jean-edouard** [comment]
The build failed because something happened in the Windows build VM. I salvaged the build output, which should have everything but Windows tools: http://openxt.ainfosec.com/builds/custom/master/916/

**Comment by dpsmith** [comment]
This was included in my build and testing of forward seal from stable-6 to stable-7. I also tested clean install of ML stable-7 and was able to unseal on reboot.

+1

**Comment by rossphilipson** [comment]
This has been reviewed, built and tested. I say it is good to go - merging soon.

**Pull request merged**
