### PR TITLE
OXT-792: OCaml platform -> meta-openxt-ocaml-platform

### PR DESCRIPTION
**Pull request by dozylynx**
This PR will require a corresponding PR for
meta-openxt-ocaml-platform.git and a new layer definition file for
openxt.git. It will affect build sites due to the need to clone the new
OCaml repository into place for future builds.

Signed-off-by: Christopher Clark christopher.clark6@baesystems.com

### CODE REVIEW

**Comment by dozylynx** [comment]
Please could one of the repository maintainers let me know the next steps to proceed with this and the other related initial stratification PRs for Ocaml and Haskell layers -- thanks.

**Comment by jean-edouard** [comment]
See https://github.com/OpenXT/meta-openxt-qt/pull/1#issuecomment-260658637

**Comment by rneilturner** [comment]
It's not good for the image of the community to have PR's unmaintained by the originators and sitting in queue for this long. I would suggest the meta-openxt-ocaml PR's be rejected until such time as they can be properly maintained.

**Comment by dozylynx** [comment]
These PRs are in my queue to refresh next week.

**Comment by dozylynx** [comment]
From inspection, this PR remains clean to merge along with corresponding openxt PR 203: https://github.com/OpenXT/openxt/pull/203.
This PR conflicts with currently-open xenclient-oe PR #554 .

**Comment by dpsmith** [comment]
lgtm

merging soon

**Comment by jean-edouard** [comment]
Hmm, did you test this?

**Comment by dpsmith** [comment]
Yes, but you are welcome to do your own build to test as well.

**Pull request merged**
