### PR TITLE
Update Installer Dom0 RAM to 8GB

### PR DESCRIPTION
**Pull request by pearsonk**
Some systems were having issues with 64GB (one person cited issues with
50GB). 8GB is common for installed systems and is beyond sufficient for
the installer with plenty of RAM available for any debugging or
unpacking for derivative systems.

Signed-off-by: Kevin Pearson <kevin.pearson.4@us.af.mil>

### CODE REVIEW

**Comment by pearsonk** [comment]
Just some speculation on causes, the problem seen by others may stem from RAM balance and the fact that even the installer sets dom0_max_vcpus=1. My test systems had >64GB per socket available. If this is the case, a crash could still happen on a multi-socket system with <8GB per socket but why would anybody ever do that?

**Comment by pearsonk** [comment]
Tested this on a Z820 with 96GB RAM and for funsies a laptop with 16GB RAM.

**Comment by jean-edouard** [comment]
+1

**Comment by rossphilipson** [comment]
Checked that no "----" snuck in :)

Merging...

**Pull request merged**
