### PR TITLE
[OXT-272]+[OXT-271]

### PR DESCRIPTION
**Pull request by cjp256**
Depends on oxt-271, and as such, is included in this pull (although available separately).

### CODE REVIEW

**Comment by cjp256** [comment]
https://github.com/OpenXT/xenclient-oe/pull/98

**Comment by cjp256** [comment]
I do not believe so, because of --ignore-existing (which is probably good in most cases, just not this one).

**Comment by jean-edouard** [comment]
Will cp -p preserve xattrs? The manpage wasn't clear on that...

**Comment by cjp256** [comment]
Good Q.  I'd assumed the xattrs would be set correctly at file creation, being that it is copied into the right path? Perhaps I'm wrong, I'll double check it, but I didn't have selinux issues when I did before.

**Comment by cjp256** [comment]
Tested it, labels look consistent between the dom0 image and the target location.

**Comment by jean-edouard** [comment]
Great thanks, merging now.

**Pull request merged**
