### PR TITLE
refpolicy: adjust for qtdbd

### PR DESCRIPTION
**Pull request by dpsmith**
Adjust the policy for accesses qtdbd require.

OXT-787

Signed-off-by: Daniel P. Smith <dpsmith@apertussolutions.com>

### CODE REVIEW

**Comment by stephensmalley** [comment]
Looks good as far as content.  I did notice however that it was diff -Naur generated rather than quilt refresh generated so the diff style is inconsistent; might want to fix that. Note that the labeling of /sys/devices/system/cpu/online is now upstream in refpolicy too so eventually that will drop out upon a rebase.

**Comment by rossphilipson** [comment]
This was discussed and accepted as reasonable. We can merge it once the patch is reformatted.

**Comment by dpsmith** [comment]
Would it be better to break the labeling of /sys/devices/system/cpu/online into a separate patch so it can just be dropped when rebase occurs?

**Comment by dpsmith** [comment]
Patches have been refreshed using quilt.

**Comment by rossphilipson** [comment]
Ack, merging soon.

**Comment by rossphilipson** [comment]
Built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/554
Testing...

**Comment by rossphilipson** [comment]
Looks good, no issues. Merging soon.

**Pull request merged**
