### PR TITLE
OXT-1623: libxl: add back stubdom check for helper kill

### PR DESCRIPTION
**Pull request by mahantesh-ais**
OXT-1623

This check was missed when upgrading from xen-4.11

Signed-off-by: Mahantesh Salimath <salimathm@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [$6625](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6625)

**Comment by eric-ch** [comment]
So the warning is no longer there for dom0, but instead I have that same warning back at shutdown for every domain with stub-domain.

**Comment by eric-ch** [comment]
Last warning is triggered by platforms that don't have an ATAPI device to pass-through as the only criteria for this log is to try to read a Xenstore node . Not a regression.

**Comment by jean-edouard** [comment]
@mahantesh-ais, is the new change another thing that was lost in upgrade? Does that change apply to the stable-9 PR too?

**Comment by mahantesh-ais** [comment]
@jean-edouard, new commit is suggested by @eric-ch, which is to log when `kill()` fails rather than logging when read on Xenstore node fails. If all agree with this change, I can PR the change to stable-9 as well.

**Comment by eric-ch** [comment]
Build [$6631](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6631)

**Comment by eric-ch** [comment]
No more warnings, thanks!

**Pull request merged**
