### PR TITLE
STABLE-7: OXT-1187: xen: upgrade to 4.6.6

### PR DESCRIPTION
**Pull request by eric-ch**
Remove upstream XSA backports.

See release notes:
https://www.xenproject.org/downloads/xen-archives/xen-46-series/xen-466.html

### CODE REVIEW

**Comment by eric-ch** [comment]
Depends on https://github.com/OpenXT/openxt/pull/259

**Comment by dozylynx** [comment]
A stable-7 backport of OXT-1189 PR #728 is waiting on this PR going into the branch first.

**Comment by rneilturner** [comment]
Been running with 4.6.6 the past week without issue. +1

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
