### PR TITLE
OXT-1299: [xl] Use sigsuspend to synch xenmgr and xl domain

### PR DESCRIPTION
**Pull request by crogers1**
reboot.  Remove old reboot fix patch

  OXT-1299

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Merge with https://github.com/OpenXT/manager/pull/113

**Comment by mahantesh-ais** [comment]
LGTM, domain reboots are now faster and this also resolves the issues with ndvm reboot.

**Comment by eric-ch** [comment]
Build [$1498](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1498)

**Comment by eric-ch** [comment]
Xen 4.10 upgrade makes this PR conflict... sorry for the inconvenience.
Can you please refresh your patch with the [configuration provided on the wiki](https://openxt.atlassian.net/wiki/spaces/DC/pages/20905986/Dealing+with+quilt) please?

**Comment by jean-edouard** [comment]
@crogers1, please rebase.

**Comment by crogers1** [comment]
Yea I can do that tomorrow as well

**Comment by crogers1** [comment]
This has been updated to build on xen-4.10, and updated to comply with the quilt stuff

**Comment by eric-ch** [comment]
Building [$1531](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1531)

**Comment by jean-edouard** [comment]
Build here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1531

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
