### PR TITLE
xc-sha1sum redundant with busybox

### PR DESCRIPTION
**Pull request by eric-ch**
sha1sum is already provided in the initramfs by busybox, we should that
instead of having our own.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Oh yeah, we don't need that one anymore, since we just added busybox to the initramfs like 4 years ago :)

**Comment by rossphilipson** [comment]
+1

**Comment by jean-edouard** [comment]
`sha1sum` prints out the hash followed by the filename, as opposed to `xc-sha1sum` that just prints the hash.
It's probably preferable to use only the hash, so some cutting action might be needed here.

**Comment by eric-ch** [comment]
@jean-edouard indeed... fixed. I'll test it correctly this time.

**Comment by jean-edouard** [comment]
LGTM now, included in http://158.69.227.117/builds/master/custom-dev-14-master/
Will merge later today.

**Pull request merged**
