### PR TITLE
Make sure there is buffer control on high memory pages

### PR DESCRIPTION
**Pull request by rneilturner**
Signed-off-by: turnerr <turnerr@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
@rneilturner does this fix a particular issue? Is there a way to test the fix? Thanks

**Comment by rneilturner** [comment]
It fixes an issue when Dom0 has available high memory and a page within the scatter list is referencing said high memory. When you try to get this page address it will fail in spectacular fashion, usually corrupting the tap disk along the way. The best way to reproduce this issue is increase the Dom0 memory size above the low memory size, usually somewhere above 896M minus what you have allocated for vmalloc. Once you have this you can go about it in a couple of ways. Keep on rebooting the box until VM's start failing, run a script which mounts and unmounts a created tap disk - you will see the sha256sum of the mounted bzImage change. We have also noticed this problem occurs more frequently on dual-processor machines.

**Comment by richpersaud** [comment]
Does this affect both blktap2 and blktap3?  Is this intended for stable-8?

**Comment by rneilturner** [comment]
I haven't tested this on blktap2 but it does impact blktap3. Once this PR is +1 I will submit a PR against stable-8.

**Comment by jandryuk** [comment]
@rneilturner, your description of the problem is good and belongs in the commit message for the change.  Thanks.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1837

**Comment by jean-edouard** [comment]
LGTM. @rneilturner please amend the commit message and I'll merge this.

**Comment by rneilturner** [comment]
Sorry for the late response, I have been on travel. I will update the PR description tonight as mentioned by @jandryuk

**Comment by rneilturner** [comment]
PR description has been updated.

**Comment by jean-edouard** [comment]
Merging soon

**Pull request merged**
