### PR TITLE
Use do_deploy for installer part2

### PR DESCRIPTION
**Pull request by jandryuk**
Installer part 2 is a collection of shell scripts.  Currently it is packaged into an xenclient-installer-part2.ipk and then installed into xenclient-installer-part2-image to be repackages as a .tar.bz2.  Skip using the part2-image and just create the tarball directly with do_deploy making it accessible outside the build.

### CODE REVIEW

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/10/builds/10): [mcq-10](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom-quick/10)

**Review by eric-ch — APPROVED** [review]
LGTM

**Comment by jandryuk** [comment]
This will supersede the need for https://github.com/OpenXT/xenclient-oe/pull/1329

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
