### PR TITLE
Revert "STABLE-7: OXT-1255: XSA 246 & 247"

### PR DESCRIPTION
**Pull request by jean-edouard**
Reverts OpenXT/xenclient-oe#808

### CODE REVIEW

**Comment by jean-edouard** [comment]
These XSAs are about a feature that's not enabled in OpenXT (Populate on Demand).
Since we're very late in the release process of OpenXT 7.0.0, a lot of testing has already been done without these patches, so I suggest we remove them, at least for now.

**Comment by dpsmith** [comment]
Another option to consider is that since testing thus far is against the RC2 tag, testing can finish against that tag the revision hash can be used for the 7.0.0 tag. I suggest this since there are four more XSA's coming tomorrow which as soon as 7.0.0 is released, theses two will need to be pulled right back in along with the four new ones for a 7.0.1 release. Thoughts?

**Comment by MagOXT** [comment]
+1 for regression testing on RC2

**Comment by jean-edouard** [comment]
@dpsmith that would work only as long as no critical issue is found in RC2... It also breaks my release script but I can fix that.
Your call, please approve/disapprove and someone will merge/close this PR.
Thanks

**Pull request merged**
