### PR TITLE
Stable-6: xen: XSA-154 & XSA-182

### PR DESCRIPTION
**Pull request by eric-ch**

### CODE REVIEW

**Comment by richpersaud** [comment]
Would be good to have a JIRA ticket to assist in compilation of 6.0.0 release notes.

**Comment by eric-ch** [comment]
@richpersaud indeed, OXT-682.

**Comment by rneilturner** [comment]
Tested on our downstream derivative without issue so far. This included GPU passthrough, win7/10 guests, networking, stubdom & non-stubdom support.

**Comment by rossphilipson** [comment]
Tested on stable-6 too. Will merge soon.

**Pull request merged**
