### PR TITLE
initscripts: remove initscript code that's incompatible with read-only rootfs

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/70

**Comment by dozylynx** [comment]
Purely out of curiosity: do you know what the file `/etc/.configured` was used by?

**Comment by jean-edouard** [comment]
Sorry I don't...

**Comment by dozylynx** [comment]
Didn't find anything other than the references in this PR with grepping over the dom0 and ndvm rootfs, and a few of the source repos. Oh well, a mystery then.

**Comment by rossphilipson** [comment]
According to the comment from the commit where it was introduced in 2012:

"[initscripts] add missing files from old OE"

**Comment by eric-ch** [comment]
LGTM, it removes a lot of log regarding failure to write files.
Will merge soon.

**Pull request merged**
