### PR TITLE
[OXT-238] generic xenstore patch

### PR DESCRIPTION
**Pull request by cjp256**

### CODE REVIEW

**Comment by jean-edouard** [comment]
LGTM.
I assume this use case is too specific to use libxcxenstore (https://github.com/OpenXT/xclibs/tree/master/xcxenstore), right?

**Comment by brendank310** [comment]
+1 from me when the recipe INC_PR is bumped up.

**Comment by cjp256** [comment]
Yeah, most of the xenstore functions are already provided in xen_backend.c. This is just so other bits can use them (e.g. atapi-pt) as well as to provide a way to make sure they are ready to be used (before xen_be_init() is called) with xenstore_generic_init().

**Comment by cjp256** [comment]
Pushed fix for 0025 refresh.

**Comment by brendank310** [comment]
+1 with the latest commits

**Comment by crogers1** [comment]
+1.

**Pull request merged**
