### PR TITLE
initscripts: remove bootmisc.sh overrides

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-609

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
This breaks hostnames, for some reason dom0 and uivm are missing `/etc/init.d/hostname.sh`.
NDVM has it. This PR still stands, what it fixes is more important than what it breaks...

**Comment by jean-edouard** [comment]
Found it, added a commit.

**Comment by rossphilipson** [comment]
So this built w/o a problem: http://158.69.127.133:8020/builders/openxt-custom/builds/90

Not sure exactly how to test it.

**Comment by rossphilipson** [comment]
Removing these scripts removes these lines:
`[ -f /etc/hostname ] && hostname -F /etc/hostname`
Which results in dom0 and the uivm having no hostname in a terminal:
`root@(none):~#`
Not sure if that is intended or desired...

**Comment by jean-edouard** [comment]
@rossphilipson see previous comments.
Build 90 misses the second commit.

**Comment by rossphilipson** [comment]
Built here:
http://158.69.127.133:8020/builders/openxt-custom/builds/105
Installed and booted, everything looks happy now. Merging soon....

**Pull request merged**
