### PR TITLE
OXT-581 Xen 4.6.1 uprev (OXT-589 - Debranding)

### PR DESCRIPTION
**Pull request by mbgrego**
OXT-581 Xen 4.6.1 uprev. It requires "Xen 4.6.1 uprev toolstack changes" pull request for the toolstack and "[xen-4.6] Use Xen 4.6 in OpenXT" pull request to be merged at the same time.

OXT-589 Additionally XenClient XT branding was removed

### CODE REVIEW

**Comment by rossphilipson** [comment]
@jean-edouard started a build of this here (almost done):
http://158.69.127.133:8020/builders/openxt-custom/builds/130

**Comment by rossphilipson** [comment]
@mbgrego the build failed while building the tools packages for Linux using the old method and do_build.sh. The problem is that the environment variable AWK is not defined so some of the xen flask scripts die. The solution (at least to get things working) is to define it - e.g. at the top of this script:

https://github.com/OpenXT/openxt/blob/master/pkg-xctools/build.sh

add

export AWK=/usr/bin/awk

I know that is ugly but these scripts are quickly becoming obsolete so I think that is fine.

**Comment by rossphilipson** [comment]
I guess I can submit a PR for that just to get another build going

**Comment by rossphilipson** [comment]
Ok I added it to my openxt.git PR:

https://github.com/OpenXT/openxt/pull/175/commits

**Comment by rossphilipson** [comment]
New one in the oven:
http://158.69.127.133:8020/builders/openxt-custom/builds/132

**Comment by jean-edouard** [comment]
The installer doesn't boot on both my HP Skylake laptop and Skylake desktop.
Here's what I get on serial:
```
 Xen 4.6.1-xc
(XEN) Xen version 4.6.1-xc (build@) (gcc (Debian 4.9.2-10) 4.9.2) debug=n Mon Aug 15 15:36:43 EDT 2016
(XEN) Latest ChangeSet: 
(XEN) Bootloader: PXELINUX 6.03 PXE 20150819 
(XEN) Command line: console=com1,vga max_dom0_vcpus=1 com1=115200,8n1,pci dom0_mem=max:8G
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN)  VBE/DDC methods: V2; EDID transfer time: 1 seconds
(XEN) Disc information:
(XEN)  Found 1 MBR signatures
(XEN)  Found 1 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  0000000000000000 - 000000000009dc00 (usable)
(XEN)  000000000009dc00 - 00000000000a0000 (reserved)
(XEN)  00000000000e0000 - 0000000000100000 (reserved)
(XEN)  0000000000100000 - 00000000acacf000 (usable)
(XEN)  00000000acacf000 - 00000000acad0000 (ACPI NVS)
(XEN)  00000000acad0000 - 00000000acb1a000 (reserved)
(XEN)  00000000acb1a000 - 00000000c90fb000 (usable)
(XEN)  00000000c90fb000 - 00000000c9c7f000 (reserved)
(XEN)  00000000c9c7f000 - 00000000c9e7f000 (ACPI NVS)
(XEN)  00000000c9e7f000 - 00000000c9eff000 (ACPI data)
(XEN)  00000000c9eff000 - 00000000c9f00000 (usable)
(XEN)  00000000c9f00000 - 00000000ce800000 (reserved)
(XEN)  00000000f8000000 - 00000000fc000000 (reserved)
(XEN)  00000000fd000000 - 00000000fe800000 (reserved)
(XEN)  00000000fec00000 - 00000000fec01000 (reserved)
(XEN)  00000000fed00000 - 00000000fed01000 (reserved)
(XEN)  00000000fed10000 - 00000000fed1a000 (reserved)
(XEN)  00000000fed84000 - 00000000fed85000 (reserved)
(XEN)  00000000fedb0000 - 00000000fedc0000 (reserved)
(XEN)  00000000fee00000 - 00000000fee01000 (reserved)
(XEN)  00000000ff700000 - 0000000100000000 (reserved)
(XEN)  0000000100000000 - 000000042f800000 (usable)
(XEN) ACPI: RSDP 000FBE20, 0024 (r2 HPQOEM)
(XEN) ACPI: XSDT C9EFD0E8, 00AC (r1 HPQOEM SLIC-BPC        0       1000013)
(XEN) ACPI: FACP C9EF2000, 00F4 (r5 HPQOEM SLIC-BPC        0 HP          1)
(XEN) ACPI: DSDT C9ED1000, 1D989 (r2 HPQOEM 8053            0 INTL 20121018)
(XEN) ACPI: FACS C9E5A000, 0040
(XEN) ACPI: SSDT C9EFC000, 0108 (r2 HP     ShmTable        1 INTL 20121018)
(XEN) ACPI: TCPA C9EFB000, 0032 (r2 HPQOEM EDK2            2       1000013)
(XEN) ACPI: SSDT C9EFA000, 03B8 (r2 HPQOEM TcgTable     1000 INTL 20121018)
(XEN) ACPI: UEFI C9E66000, 0042 (r1 HPQOEM EDK2            2       1000013)
(XEN) ACPI: SSDT C9EF4000, 51FA (r2 SaSsdt  SaSsdt      3000 INTL 20121018)
(XEN) ACPI: SSDT C9EF3000, 05B1 (r1  Intel PerfTune     1000 INTL 20121018)
(XEN) ACPI: HPET C9EF1000, 0038 (r1 HPQOEM 8053            1 HP          1)
(XEN) ACPI: APIC C9EF0000, 00BC (r1 HPQOEM 8053            1 HP          1)
(XEN) ACPI: MCFG C9EEF000, 003C (r1 HPQOEM 8053            1 HP          1)
(XEN) ACPI: SSDT C9ED0000, 019A (r2 HPQOEM Sata0Ide     1000 INTL 20121018)
(XEN) ACPI: SSDT C9ECF000, 0729 (r1 HPQOEM PtidDevc     1000 INTL 20121018)
(XEN) ACPI: SSDT C9ECE000, 0E6E (r2 CpuRef  CpuSsdt     3000 INTL 20121018)
(XEN) ACPI: DMAR C9ECD000, 00A8 (r1 INTEL      SKL         1 INTL        1)
(XEN) ACPI: ASF! C9ECC000, 00A5 (r32 HPQOEM      UYA        1 TFSM    F4240)
(XEN) ACPI: FPDT C9ECB000, 0044 (r1 HPQOEM EDK2            2       1000013)
(XEN) ACPI: BGRT C9ECA000, 0038 (r1 HPQOEM EDK2            2       1000013)
(XEN) System RAM: 16264MB (16654648kB)
(XEN) Domain heap initialised
(XEN) ACPI: 32/64X FACS address mismatch in FADT - c9e5a000/0000000000000000, using 32
(XEN) Processor #0 7:14 APIC version 21
(XEN) Processor #2 7:14 APIC version 21
(XEN) Processor #4 7:14 APIC version 21
(XEN) Processor #6 7:14 APIC version 21
(XEN) Processor #1 7:14 APIC version 21
(XEN) Processor #3 7:14 APIC version 21
(XEN) Processor #5 7:14 APIC version 21
(XEN) Processor #7 7:14 APIC version 21
(XEN) IOAPIC[0]: apic_id 2, version 32, address 0xfec00000, GSI 0-119
(XEN) Enabling APIC mode:  Flat.  Using 1 I/O APICs
(XEN) Not enabling x2APIC (upon firmware request)
(XEN) XSM Framework v1.0.0 initialized
(XEN) xstate_init: using cntxt_size: 0x440 and states: 0x1f
(XEN) Using scheduler: SMP Credit Scheduler (credit)
(XEN) Detected 3419.856 MHz processor.
(XEN) Initing memory sharing.
(XEN) Intel VT-d iommu 0 supported page sizes: 4kB, 2MB, 1GB.
(XEN) Intel VT-d iommu 1 supported page sizes: 4kB, 2MB, 1GB.
(XEN) Intel VT-d Snoop Control not enabled.
(XEN) Intel VT-d Dom0 DMA Passthrough not enabled.
(XEN) Intel VT-d Queued Invalidation enabled.
(XEN) Intel VT-d Interrupt Remapping enabled.
(XEN) Intel VT-d Shared EPT tables enabled.
(XEN) I/O virtualisation enabled
(XEN)  - Dom0 mode: Relaxed
(XEN) Interrupt remapping enabled
(XEN) Enabled directed EOI with ioapic_ack_old on!
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using old ACK method
(XEN) Platform timer is 23.999MHz HPET
(XEN) Allocated console ring of 16 KiB.
(XEN) VMX: Supported advanced features:
(XEN)  - APIC MMIO access virtualisation
(XEN)  - APIC TPR shadow
(XEN)  - Extended Page Tables (EPT)
(XEN)  - Virtual-Processor Identifiers (VPID)
(XEN)  - Virtual NMI
(XEN)  - MSR direct-access bitmap
(XEN)  - Unrestricted Guest
(XEN)  - VMCS shadowing
(XEN)  - VM Functions
(XEN)  - Virtualisation Exceptions
(XEN) HVM: ASIDs enabled.
(XEN) HVM: VMX enabled
(XEN) HVM: Hardware Assisted Paging (HAP) detected
(XEN) HVM: HAP page sizes: 4kB, 2MB, 1GB
(XEN) Brought up 8 CPUs
(XEN) Dom0 has maximum 888 PIRQs
(XEN) *** LOADING DOMAIN 0 ***
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 32-bit, PAE, lsb, paddr 0x1000000 -> 0x1b1b000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000418000000->000000041c000000 (2053282 pages to be allocated)
(XEN)  Init. ramdisk: 0000000428ca2000->000000042f7ffc00
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: 00000000c1000000->00000000c1b1b000
(XEN)  Init. ramdisk: 0000000000000000->0000000000000000
(XEN)  Phys-Mach map: 00000000c1b1b000->00000000c231b000
(XEN)  Start info:    00000000c231b000->00000000c231b4b4
(XEN)  Page tables:   00000000c231c000->00000000c2333000
(XEN)  Boot stack:    00000000c2333000->00000000c2334000
(XEN)  TOTAL:         00000000c0000000->00000000c2400000
(XEN)  ENTRY ADDRESS: 00000000c17ff254
(XEN) Dom0 has maximum 8 VCPUs
(XEN) Scrubbing Free RAM on 1 nodes using 4 CPUs
(XEN) ..................................done.
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) Xen is relinquishing VGA console.
(XEN) *** Serial input -> DOM0 (type 'CTRL-a' three times to switch input to Xen)
(XEN) Freed 300kB init memory.
mapping kernel into physical memory
about to get started...
[    0.000000] IOAPIC[0]: Unable to change apic_id!
[    5.344173] Error: Driver 'processor_aggregator' is already registered, aborting...
[   67.481989] INFO: rcu_sched self-detected stall on CPU
[   67.482014] 	5-...: (6000 ticks this GP) idle=629/140000000000001/0 softirq=216/216 fqs=5998 
[   67.482017] 	 (t=6001 jiffies g=-280 c=-281 q=18)
```

**Comment by mbgrego** [comment]
I do not have any Skylake hardware to fix this problem.

**Comment by rossphilipson** [comment]
I am looking at this now. It also happens on my Dell Broadwell laptop.

**Comment by mbgrego** [comment]
I have been testing on Ivy Bridge. I will see if I can find some "newer" hardware.

**Comment by rossphilipson** [comment]
I have tracked the problem down to an incompatibility with Xen using the SMAP feature on Broadwell+ systems and 32b PV guests (ie dom0). I have a temporary workaround and a fix - I will create a ticket to track both. The workaround will let us get these PRs in w/o introducing a regression. The fix will allow us to have the SMAP security feature available in OpenXT.

**Comment by rossphilipson** [comment]
This PR must go in with this too:
https://github.com/OpenXT/xenclient-oe/pull/398

**Comment by jean-edouard** [comment]
That PR fixed it, all good now, merging soon.

**Comment by rossphilipson** [comment]
+1 - tested on a Broadwell w/ ML. Created guests, all good.

**Pull request merged**
