### PR TITLE
linux-openxt: Version bump to 4.9.27

### PR DESCRIPTION
**Pull request by jandryuk**
OXT-1099

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Could you refresh the patch-queue to attend the few Hunks offsets here and there?
LGTM otherwise.
Building: [838](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/838)

**Comment by jandryuk** [comment]
Refreshed.

For the original PR, I checked log.do_patch, but it didn't show any hunk offsets.  Default logging must not capture those.

**Comment by jandryuk** [comment]
Also, I only refreshed those patches needing offset updates to eliminate noise from file path changes.

**Comment by eric-ch** [comment]
@jandryuk Indeed, the log.do_patch does not seem to capture Hunk offset. Thanks for the refresh.
Build [838](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/838) failed for irrelevant reasons.
New build is [839](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/839).

**Comment by eric-ch** [comment]
Tested build [839](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/839) on E6440 (create Windows guest, install tools, platform S3,...).
LGTM, +1, will merge soon.

**Pull request merged**
