### PR TITLE
OXT-1564: Remove /etc/modules from installer image.

### PR DESCRIPTION
**Pull request by eric-ch**
Change how `/etc/modules` is packaged to make it machine agnostic and use a different recipe per image.
`modules-installer` is removed since the installer does not deploy any module.
This silence spurious warning during the installation bootstrap.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6522

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Comment by jean-edouard** [comment]
stable-9?

**Comment by eric-ch** [comment]
@jean-edouard https://github.com/OpenXT/xenclient-oe/pull/1137

**Pull request merged**
