### PR TITLE
STABLE-9: OXT-1642: [nss] Upgrade nss to 3.45

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1642

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>
(cherry picked from commit 113a5d67e2860b88fab933e35082133f557497c8)

### CODE REVIEW

**Comment by crogers1** [comment]
Updated with patch to fix pesign compilation failure

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6675

**Comment by jean-edouard** [comment]
Merging soon.

**Comment by jean-edouard** [comment]
Note: leaving the master PR open, see https://github.com/OpenXT/xenclient-oe/pull/1215#issuecomment-516135814

**Pull request merged**
