### PR TITLE
STABLE-6: OXT-1218: Upgrade Xen to 4.6.6.

### PR DESCRIPTION
**Pull request by eric-ch**
Most of the work was done in master before switching to libxl (and branching stable-7).
Linked to:
- https://github.com/OpenXT/openxt/pull/267
- https://github.com/OpenXT/toolstack/pull/31

### CODE REVIEW

**Comment by jean-edouard** [comment]
@eric-ch, conflict alert.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1189

**Comment by jean-edouard** [comment]
@eric-ch Works perfectly, just one question, why all the libxl patches?

**Comment by eric-ch** [comment]
@jean-edouard No reason, I'll remove that.

**Comment by eric-ch** [comment]
@jean-edouard Done, building [1202](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1202)

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
