### PR TITLE
[xenclient-boot-sound] fix config before adjusting the volumes

### PR DESCRIPTION
**Pull request by jean-edouard**
update-pcm-config fixes the alsa config, which is needed to be able to access the volumes.

### CODE REVIEW

**Comment by rianquinn** [comment]
The patch looks good to me. The only thing I would change in addition to what is there, is the set should really be "sset" instead, as amixer's proper syntax is "sset" and "sget".

**Comment by jean-edouard** [comment]
I think that second fix belongs to a separate pull request

**Comment by rianquinn** [comment]
thats fine... I will still do it though.

**Comment by rianquinn** [comment]
There probably should be two fixes to this script. I'm going to create a JIRA ticket to address both issues, so that we can create a fix and separate pull request.

**Comment by rossphilipson** [comment]
LGTM

**Pull request merged**
