### PR TITLE
Layer clean up

### PR DESCRIPTION
**Pull request by dpsmith**
This cleans up the recipe-openxt folder to align with OE conventions on layer layout. In particular all OpenXT specific recipes have been moved out of recipes-openxt/xenclient to a proper folder structure under recipes-openxt. Any recipes for upstream components in recipes-openxt have been moved to the appropriate recipes folder.

OXT-580

Signed-off-by: Daniel P. Smith <dpsmith@apertussolutions.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1837

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Comment by jean-edouard** [comment]
@dpsmith, sorry, https://github.com/OpenXT/xenclient-oe/pull/1071 broke this, could you please rebase? Thanks

**Comment by dpsmith** [comment]
Rebased onto master.

**Comment by jean-edouard** [comment]
We messed up and merged another PR that breaks this one... Could you please re-rebase? Sorry about that.

**Comment by dpsmith** [comment]
No worries! I did a quick rebase and manual review. Would recommend doing another test build just to confirm.

**Comment by eric-ch** [comment]
Building [$1846](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1846)

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
