### PR TITLE
STABLE-7: OXT-1255: XSA 246 & 247

### PR DESCRIPTION
**Pull request by jandryuk**
This adds the patches for XSA 246 and 247.  While in there, I re-ordered the patch queue to keep all the XSAs at the end.  I made a separate commit for the refresh of xsa246-4.7.patch to clearly distinguish adding the upstream patch and making a modification to apply cleanly.

OXT-1255

### CODE REVIEW

**Comment by jean-edouard** [comment]
@jandryuk we usually submit these against master first, and then cherry-pick to stable-7.

**Comment by jandryuk** [comment]
Isn't master on 4.9 and stable-7 on 4.6?

**Comment by jean-edouard** [comment]
Correct, it probably won't be a straight cherry-pick in this case...
I guess it's fine to do stable-7 first as long as we don't forget master.

**Comment by eric-ch** [comment]
@jean-edouard Actually master should uprev to Xen 4.9.1 and add the missing XSA.

**Comment by jandryuk** [comment]
I have a test build for master/Xen 4.9 running here.  If all goes well, I'll push up a master PR tomorrow morning.

**Comment by eric-ch** [comment]
@jandryuk Thanks!

Building [#1260](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1260)

**Comment by jandryuk** [comment]
I just added the XSA patches.  I can re-work for a 4.9.1 uprev if desired.

**Comment by eric-ch** [comment]
@jandryuk that would be ideal, but could also be done later if you have something else on your plate.

**Comment by eric-ch** [comment]
LGTM, will merge soon.

**Pull request merged**
