### PR TITLE
OXT-1642: [nss] Upgrade nss to 3.45

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1642

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Failed to build: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6666/steps/Build/logs/stdio

**Comment by crogers1** [comment]
Hmmm, looking into it.

**Comment by crogers1** [comment]
Updated with patch to fix pesign compilation failure

**Comment by eric-ch** [comment]
Build ($6691)[http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6691]

**Comment by crogers1** [comment]
@eric-ch is there anything else you need from me for this PR?

**Comment by eric-ch** [comment]
@crogers1 All good.

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
