### PR TITLE
OXT-1426: l1tf: Disable SMT on Xen.

### PR DESCRIPTION
**Pull request by eric-ch**
Following XSA-273:
- Risk assessment:
1) Hyper-threading is available on most platform tested with OpenXT.
2) OpenXT does not use exclusively PV or HVM Shadow guests.
3) HVM guests kernels running in OpenXT are not always trusted.
4) Untrusted HVM guest kernel can run on OpenXT.

- Finer grained
OpenXT UI does not offer the possibility to use vm.cpumask, vm.hvm.cpumask and vm.pv.cpumask.
OpenXT does not leverage vm.cpumask, vm.hvm.cpumask and vm.pv.cpumask as
of now.

Disabling SMT unconditionally is recommended, pass the argument to Xen
command-line.

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [$1772](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1772)

**Comment by eric-ch** [comment]
Build [$1776](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1776)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1782

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
