### PR TITLE
linux: dom0: enable I2C HID support, and drivers for Haswell-ULT cont…

### PR DESCRIPTION
**Pull request by jean-edouard**
…rollers

OXT-396

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
LGTM, please add OXT-396 in the commit message though :).

**Comment by ktemkin** [comment]
+1; LGTM

**Comment by rossphilipson** [comment]
Has anyone tried this fix out - tested it?

**Comment by rossphilipson** [comment]
Also if we are ultimately going to move to say 4.3, won't we pick this stuff up there?

**Comment by ktemkin** [comment]
@rossphilipson:
I haven't built with this PR exactly, but I do have a build with those options turned on-- they enable touch support for more modern touchscreen platforms (Dell Venue 11, Dell 7350, etc.). 

I'm not sure what you mean by "won't we pick this stuff up [in 4.3]". This looks to me like it's just turning on configuration options that aren't set by default-- this change should be necessary no matter what kernel version we use.

**Comment by rossphilipson** [comment]
Oh sorry I got this confused with something else (a back port). My bad.

**Comment by jean-edouard** [comment]
@eric-ch, done

**Comment by rossphilipson** [comment]
Ok then. Two +1s and @ktemkin has been running w/ those options on. Merging.

**Pull request merged**
