### PR TITLE
initramfs: use busybox instead of busybox-static

### PR DESCRIPTION
**Pull request by cjp256**
Upstream oe-core does not use busybox-static for their
images, and it does not appear to be required for the
dom0 initramfs to function.

As the initramfs is the only user of busybox-static,
we can remove busybox-1.11.3 entirely now.

Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

### CODE REVIEW

**Comment by cjp256** [comment]
Tested this by building initramfs (and rebuilding dom0).  System booted OK.

Configured measured launch, caused it to trip, ensured that input continued to work during reseal/recovery process.

**Comment by rossphilipson** [comment]
I think this one needs a full build too - started one here: 
http://openxt.ainfosec.com:8020/builders/extbuilder/builds/322

**Comment by cjp256** [comment]
@rossphilipson Thanks!

I did a network install of ext build 322 and it booted fine for me.

**Comment by jean-edouard** [comment]
I bisected the two config files, and by switching to the new busybox we lose:
- syslog
- syslogd
- vi
- netcat
- telnetd
- traceroute
- dc (reverse polish calculator)

It's probably ok, I can't think of anything using any of those, but if anyone knows about a part of the initramfs using something from that list, please chime in.

**Comment by jean-edouard** [comment]
I couldn't find anything using those, I think we're good, I will merge soon.

**Pull request merged**
