### PR TITLE
linux: add a couple of USB NIC drivers for the installer

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Will merge soon

**Comment by dozylynx** [comment]
Is there a JIRA ticket relevant to this change?

If the Installer needs USB network device drivers in the kernel then it would make sense to have distinct separate kernels for the Installer and Dom0, to enable reduction of the Dom0 attack surface by omitting the unnecessary drivers from the Dom0 kernel.

**Comment by jean-edouard** [comment]
dom0 doesn't include any of the NIC drivers.
They are all built as modules and included only in the installer.

**Comment by dozylynx** [comment]
thanks, @jean-edouard -- excellent.

**Pull request merged**
