### PR TITLE
Fix missing RDEPENDS that broke snapshot functionality.

### PR DESCRIPTION
**Pull request by rossphilipson**
OXT-785

Signed-off-by: Ross Philipson <philipsonr@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
xen-blktap does not ship a script, so RDEPEND on bash is not required.

**Comment by rossphilipson** [comment]
You must be confused, bash is not in the RDEPENDS

**Comment by eric-ch** [comment]
https://goo.gl/Hzu3nD

LGTM.

**Comment by rneilturner** [comment]
Building now, will test in the morning.

**Comment by eric-ch** [comment]
@rneilturner Did you have the chance to give it a try? If so, are you ok with it being merged?

**Comment by rneilturner** [comment]
This resolved the issue with snapshot in Dom0, thank you @rossphilipson! I'm still seeing the same error within the syncvm when it creates the snapshot disks. I would merge this and please keep the ticket open until I can figure out why the syncvm is still returning an error code for vcd-util.

**Comment by rneilturner** [comment]
I looked at the synchronizer problem a little bit this afternoon and I'm pretty sure the cause is the lack of ICBINN support. When we moved to xen-blktap, we didn't carry forward the changes we made to support ICBINN in vhd-util. I get an error within the synchronizer indicating the vhd files can't be found. My assumption is the vhd-util we are now using can't community over ICBINN.

**Comment by rossphilipson** [comment]
@rneilturner probably better to put the comments in the ticket at this point since this PR is closed. I can respond there...

**Pull request merged**
