### PR TITLE
Enable the fdisk advanced disk option for expert mode

### PR DESCRIPTION
**Pull request by rneilturner**
In our default configuration of busybox, we don't enable the CONFIG_FEATURE_FDISK_ADVANCED, which enables the expert mode needed for realigning the partition during install. During initial install the realignment step fails and the first sector is not moved, thereby causing issues for dmsetup. 

Signed-off-by: Richard Turner <turnerr@ainfosec.com>

### CODE REVIEW

**Comment by cjp256** [comment]
LGTM

**Comment by richpersaud** [comment]
Given the complexity of triage and implications for upgrade, it would be helpful to have a JIRA ticket where relevant information can be compiled and linked to additional work that may be needed.

Does this affect only master, e.g. do we know if/why previous releases did not exhibit this failure mode?  

Does this affect only the Dell 9010, only specific disks/controllers on the 9010, or all devices/disks?

**Comment by jean-edouard** [comment]
+1
See https://openxt.atlassian.net/wiki/display/~jed/Busybox+overview

**Comment by jean-edouard** [comment]
Will merge soon.

**Comment by richpersaud** [comment]
Can we please have further documentation/discussion of the upgrade implications before merging, either on the mailing list or in a JIRA ticket?

**Comment by jean-edouard** [comment]
Sure, but the installer is basically broken without this fix, so please don't take too long.

**Comment by rneilturner** [comment]
See OXT-534.

@richpersaud see your answers below

Does this affect only master, e.g. do we know if/why previous releases did not exhibit this failure mode?

RT - This option was enabled in previous versions of OXT (pre-Jethro). During the up rev to Jethro this option was disabled causing the installer issue.

Does this affect only the Dell 9010, only specific disks/controllers on the 9010, or all devices/disks?

RT - This problem is not platform specific. It really came down to how large your core boot loader ended up being. If it was greater than 24k it would break your install and not work. In our case the boot loader image was 32k. Also, this change does not break the upgrade case.

**Comment by jean-edouard** [comment]
(moved "wiki" page to https://openxt.atlassian.net/wiki/display/DC/Busybox+overview)

**Comment by richpersaud** [comment]
Thanks for responses, ok to merge.

**Comment by jean-edouard** [comment]
Thanks, merging soon!

**Pull request merged**
