### PR TITLE
Remove the remaining currency expirations from the icedtea utility.

### PR DESCRIPTION
**Pull request by crogers1**
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
That looks fine to me. If someone else who is involved wants to +1 this, I will merge it.

**Comment by ktemkin** [comment]
+1.

Justed tested this, LGTM. You might want to bump the PR on the relevant recipe so broken builds automatically fix themselves-- but otherwise looks good.

**Comment by crogers1** [comment]
It doesn't look like we have the full recipe in our repos; there's just a bbappend, and that doesn't have a PR defined.

**Comment by crogers1** [comment]
As per Kyle's suggestion, just append to the PR to indicate a new version.

**Comment by jean-edouard** [comment]
LGTM, merging to fix the build

**Pull request merged**
