### PR TITLE
OXT-1021: file: use source tarball from tagged releases.

### PR DESCRIPTION
**Pull request by eric-ch**
Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>

### CODE REVIEW

**Comment by dpsmith** [comment]
Were you able to successful build yourself? The recipe is straightforward enough that if you were able to build with it, then I would be willing to sign off.

**Comment by jean-edouard** [comment]
LGTM, builds in my tree.

**Comment by jean-edouard** [comment]
The two tarballs are vastly different, since the actual release tarball is autoconf-ed, when the GitHub one is not. Some seemingly generated code in the .c files is also different, but it should only be slight cosmetic differences.

**Comment by dpsmith** [comment]
Are you still good with it then?

**Comment by jean-edouard** [comment]
Yes, just thought it was worth mentioning.

**Comment by rossphilipson** [comment]
RM Signed-off-by: Ross Philipson philipsonr@ainfosec.com

**Pull request merged**
