### PR TITLE
libxl: atapi-pt: use incremental device numbers instead of 0

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1102

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
+1

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/885

**Comment by rossphilipson** [comment]
Smoking now...

**Comment by rossphilipson** [comment]
Tested with built in ATAPI, USB CD, ISO and HDD in guest and it works. So we are basically at parity with stable-6. Merging soon.

**Pull request merged**
