### PR TITLE
Changed the linux recipes' PR variable from 1 to r1 to follow OE conv…

### PR DESCRIPTION
**Pull request by brendank310**
…ention

Signed-off-by: Brendan Kerrigan <kerriganb@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Does that fix anything in particular or is it aesthetics?
+1 for both cases I guess :)

**Comment by brendank310** [comment]
I was getting parse failures when using bbappends in another layer against the recipes with PR = "1", where PR = "r1" parsed fine.

**Comment by jean-edouard** [comment]
Makes sense. @eric-ch no objection?

**Comment by eric-ch** [comment]
@jean-edouard None :)
+1

**Pull request merged**
