### PR TITLE
OXT-877 & OXT-878: Upgrade Xen and port latest XSAs.

### PR DESCRIPTION
**Pull request by eric-ch**
Upgrade Xen to 4.6.4.
Port latest XSAs.

### CODE REVIEW

**Comment by eric-ch** [comment]
See openxt.git related PR: https://github.com/OpenXT/openxt/pull/208

**Comment by eric-ch** [comment]
Rebased post XL merge.

**Comment by eric-ch** [comment]
[Build](http://158.69.127.133:8020/builders/openxt-custom/builds/241).
[Images](http://openxt.ainfosec.com/builds/master/custom-dev-241-master/)

**Comment by jean-edouard** [comment]
Testing now

**Comment by jean-edouard** [comment]
LGTM, though the custom build doesn't include the new measured launch code.
Please rebase and rebuild.
Thanks

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/541
All good, merging soon.

**Pull request merged**
