### PR TITLE
[linux][blkback] fix memory leaks by backporting the code from Linux …

### PR DESCRIPTION
**Pull request by jean-edouard**
…3.18.13

OXT-289

Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by cjp256** [comment]
Have test steps to validate that memory is not leaking between reboots? (Without rebooting until something crashes? :))

Building now for testing..

**Comment by jean-edouard** [comment]
I did 900 reboots of a Ubuntu VM (no stubdom, no tools) on a laptop, and now 106 (and counting) reboots of a Windows 7 64 bits VM (stubdom + tools) on the same laptop, without ever rebooting the platform. No leak, 236MB of RAM used at the moment.

**Comment by rossphilipson** [comment]
Reviewed the patch. It is rather complicated so I don't understand all of it but the bits that changed LGTM. There is a new "feature" that got added - a xenstore flag to disable discard IO. It looks like it does not change the behavior though - if the flag is not in xenstore it behaves as before.

**Comment by cjp256** [comment]
LGTM and testing is going well.  +1, merging

**Pull request merged**
