### PR TITLE
OXT-1301: xl: fix network detach

### PR DESCRIPTION
**Pull request by mahantesh-ais**
xl network-detach is currently broken, seems like changes were missed while porting to xen-4.9

Signed-off-by: Mahantesh Salimath <mahantesh.openxt@gmail.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
LGTM, building now. This should be PR-ed against stable-8 as well.
Note: if the Xen 4.10 upgrade is merged before this PR, this one will have to be rewritten. (obviously, merging this one first will most likely break the 4.10 PR)

**Comment by jean-edouard** [comment]
This PR is not needed in master anymore, at least if Xen 4.10 gets merged.
Do not merge.

**Comment by eric-ch** [comment]
Any relationship with [OXT-1301](openxt.atlassian.net/browse/OXT-1301)?

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1474

**Comment by mahantesh-ais** [comment]
@eric-ch : This is one of the reasons why ndvm shutdown is corrupted. I'm seeing more issues during ndvm shutdown which is probably why ndvm reboot is corrupted. So, yes I discovered this problem while working on OXT-1301.

**Comment by jean-edouard** [comment]
Note: this PR brings back a line that was erroneously removed there: https://github.com/mahantesh-ais/xenclient-oe/commit/fbba145b1f5211ba4a0590a06d2a135b2a2eab84#diff-4933a1ad6748b18b7d28a44ac24d208fL72

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
