### PR TITLE
libpam: allow empty passwords

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by richpersaud** [comment]
Is there a ticket number for this change?

**Comment by jean-edouard** [comment]
No, follow this link for information on how to know if a PR has an associated ticket or not:
https://openxt.atlassian.net/wiki/spaces/DC/pages/14843935/Commit+Message+Guidelines#CommitMessageGuidelines-GeneralCommits

**Comment by richpersaud** [comment]
Thanks for the link.

What's the reasoning for allowing empty passwords?

**Comment by jean-edouard** [comment]
It's always been allowed, and required for UIVM, NDVM and unattended installs.
The Pyro PR broke that, this PR reverts PAM to the previous behavior.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1430

**Comment by eric-ch** [comment]
@richpersaud OE will let the root password empty and deactivate it when building the image ([rootfs-postcommands.bbclass](https://github.com/openembedded/openembedded-core/blob/master/meta/classes/rootfs-postcommands.bbclass)), unless explicitly allowed or for debug builds. Empty passwords are already allowed for UIVM/NDVM in https://github.com/OpenXT/xenclient-oe/commit/903f7185f9cb726687ac24629f6ce5256b88b8c7.
This PR only let PAM authorize empty password on certain TTYs.

**Comment by eric-ch** [comment]
@richpersaud [OXT-1292](https://openxt.atlassian.net/browse/OXT-1292). There is already a build configuration allowing to remove empty root passwords. Without this PR change, sshv4v is prevented to work without modifying NDVM/UIVM images on public builds, and get in the way of testing and diagnostic of almost everything else. We can take the discussion for password management on the ticket, so as to not get in the way of testing.

**Comment by eric-ch** [comment]
@richpersaud Do you agree with the approach suggested above so we can merge this?

**Comment by richpersaud** [comment]
Yes, please go ahead.

**Pull request merged**
