### PR TITLE
Upgrade linux micro to 3.18.19

### PR DESCRIPTION
**Pull request by eric-ch**
Upgrade to include upstream fixes.

backport-config-Enable-NEED_DMA_MAP_STATE-by-default-when-SWIOTLB-is-selected.patch is now upstream.

### CODE REVIEW

**Comment by rossphilipson** [comment]
Instead of doing a custom build of this, waiting for it then having one of us test this, perhaps this time we should get this PR in so everybody can start hammering on 3.18 ASAP. Thoughts?

**Comment by jean-edouard** [comment]
+1 that!

**Comment by pearsonk** [comment]
Since the merge has not yet occurred or been finalized, I'm fine with bundling it all together

**Comment by jean-edouard** [comment]
@pearsonk did I miss a 3.18 PR? :)

**Comment by pearsonk** [comment]
@jean-edouard No, I just consider what you've done so far today as in-progress

**Comment by rossphilipson** [comment]
@pearsonk so that is a +1 from you?

**Comment by pearsonk** [comment]
@rossphilipson Yes, +1 from me

**Comment by jean-edouard** [comment]
Will merge soon.

**Pull request merged**
