### PR TITLE
STABLE-5: Linux upgrade to Linux 3.18.44

### PR DESCRIPTION
**Pull request by eric-ch**

### CODE REVIEW

**Comment by dpsmith** [comment]
If I am understanding correctly, shouldn't that last commit be added to stable-6 and master?

**Comment by eric-ch** [comment]
@dpsmith Yes it should, I will send a PR in both branches today.

**Comment by rneilturner** [comment]
Building this PR against our downstream variant. Should have some testing results by tomorrow.

**Comment by eric-ch** [comment]
Stable-6 & Master PRs: https://github.com/OpenXT/xenclient-oe/pull/452 https://github.com/OpenXT/xenclient-oe/pull/453

**Comment by rneilturner** [comment]
Tested clean install, upgrade, and Win guests and it looks good. +1 this PR.

**Comment by rossphilipson** [comment]
Ok merging soon.

**Comment by rossphilipson** [comment]
Actually the build is still broken so holding off on this...

**Comment by eric-ch** [comment]
We can do that better using OE KERNELORG_MIRROR and making things easier to configure. Please do not merge yet.

**Comment by eric-ch** [comment]
See https://github.com/OpenXT/openxt/pull/204.

**Comment by jean-edouard** [comment]
Successfully built here: http://158.69.127.133:8040/builders/openxt-legacy2/builds/51
Merging soon.

**Pull request merged**
