### PR TITLE
Remove icbinn-fuse, fuse and kernel fuse support in dom0.

### PR DESCRIPTION
**Pull request by rossphilipson**
OXT-669

Signed-off-by: Ross Philipson <philipsonr@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Nothing is using fuse so the best thing to do is remove it. It built here yesterday:
http://158.69.127.133:8020/builders/openxt-custom/builds/218

**Comment by rossphilipson** [comment]
@stephensmalley there are bits in the SELinux policy that reference fuse (see ticket). Is it simply a matter of removing them since fuse is being removed?

**Comment by stephensmalley** [comment]
Doesn't look like those are adding or removing any policy related to fuse; those lines are just context lines in the diffs.  And there isn't any straightforward way to exclude all fuse-related policy, so I don't think there is anything to do here policy-wise.

**Comment by rossphilipson** [comment]
Ack, thanks.

**Comment by jean-edouard** [comment]
Tested, LGTM.
@rossphilipson Did you make sure icbinn doesn't use fuse?

**Comment by rossphilipson** [comment]
As far as I can tell, only the icbinn-fuse sub-project uses it and it is not used in openxt in any way I can find. Looking at history, it sees icbinn-fuse was some WIP that never got finished.

**Comment by jean-edouard** [comment]
Cool, merging soon then.

**Pull request merged**
