### PR TITLE
ustr: use github instead of unreliable and.org

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Note: not sure if the patches are getting applied, they don't seem to but it also doesn't seem to be a problem...

**Comment by jean-edouard** [comment]
Note2: we should consider upgrading the SELinux tools to version 2.7, which doesn't seem to require ustr anymore.

**Comment by eric-ch** [comment]
building [#1220](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1220)

**Comment by jean-edouard** [comment]
Failed to build, will have a look tomorrow.

**Comment by tklengyel** [comment]
I think this would have been a good thing, build was broken on my machine because `and.org` was down. I see applying an old patch failed on the latest master branch, but maybe that patch is just no longer needed?

**Pull request closed without merging**
