### PR TITLE
Use PREMIRRORS_append instead of overriding the SRC_URI variable.

### PR DESCRIPTION
**Pull request by crogers1**
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Alternate approach to PR: https://github.com/OpenXT/xenclient-oe/pull/70 that uses @eric-ch's recommendation.

**Comment by jean-edouard** [comment]
Can you please explain what that variable does? What's "ftp://.*/.*"?

**Comment by crogers1** [comment]
When there are extra entries in PREMIRRORS, OE will try to replace the existing url in the src_uri during the fetch step.  In the urI_replace function it decodes the urls into 2 lists and compares them.  The ftp://.*/.* is basically a regex to tell the fetcher how to parse the url and what it should match on.

For example, if you had multiple src_uris, one http, one git, and two ftp, and you wanted your PREMIRROR entry to only apply to the ftp entries, the ftp://.*/.* regex will ensure OE only replaces the ftp src_uris when attempting to fetch.

**Comment by jean-edouard** [comment]
What about the following URL?
http://sources.angstrom-distribution.org/ca-certificates_20120212.tar.gz
It looks more ... permanent...

Or shouldn't that kind of old tarball be in the mirror?

**Comment by rossphilipson** [comment]
@crogers1 - ping, Jed has a question on this - that is why it is stuck here.

**Comment by crogers1** [comment]
To be honest I wasn't really sure on this one.  Was hoping someone with more knowledge of what we wanted would chime in.

**Comment by rossphilipson** [comment]
I was told this doesn't appear to be necessary any longer. Closing.

**Pull request closed without merging**
