### PR TITLE
STABLE-6: OXT-959: Upgrade Linux to 4.4.50.

### PR DESCRIPTION
**Pull request by eric-ch**
Built in [custom-632](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/632)

### CODE REVIEW

**Comment by eric-ch** [comment]
Removing the microcode patches and defconfig support as well. It was previously disabled in the kernel defconfig.

**Comment by eric-ch** [comment]
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/712

**Comment by eric-ch** [comment]
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/714

**Comment by rossphilipson** [comment]
Tested with above build. LGTM, merging soon.

**Pull request merged**
