### PR TITLE
Remove the status-server tool and its instructions in status-report

### PR DESCRIPTION
**Pull request by dozylynx**
fixes OXT-498

### CODE REVIEW

**Comment by rossphilipson** [comment]
Are there any concerns with merging this PR and closing the ticket out?

**Comment by dozylynx** [comment]
No concerns from me.

**Comment by richpersaud** [comment]
Are we moving all dormant/inactive components to the OpenXT-extras repo, e.g. all the tickets under https://openxt.atlassian.net/browse/OXT-500?  If not, we should document which components are appropriate for OpenXT-extras.

**Comment by rossphilipson** [comment]
OpenXT-Extras is not a repo, it is an organization. Repositories that are no longer in use in OpenXT get moved there (though that is not its only use/purpose). The main reason for this (other than historical value) is to allow previous version of OpenXT to build via the Github mechanism to cache prior URLs to repositories.

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/25
+1

**Comment by rossphilipson** [comment]
+1 builds and installs - I say merge if my answer above is satisfactory for @richpersaud

**Comment by richpersaud** [comment]
Thanks for the OpenXT-extras org explanation, ok to merge.

**Pull request merged**
