### PR TITLE
[tpm2.0-tools] Convert from ascii hash to binary

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1150

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
@dpsmith will this do the job?

**Comment by dpsmith** [comment]
I believe so. Thanks!

**Comment by crogers1** [comment]
stable-7 pr: https://github.com/OpenXT/xenclient-oe/pull/698

**Comment by eric-ch** [comment]
building: [976](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/976)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1000
Merging soon.

**Pull request merged**
