### PR TITLE
usbback lockdep fixes

### PR DESCRIPTION
**Pull request by jandryuk**
This is two fixes for usbback locking issues identified by lockdep.

### CODE REVIEW

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/22/builds/19): [master-custom-19](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom/19/)

**Review by eric-ch — APPROVED** [review]
Nit: In https://github.com/OpenXT/xenclient-oe/pull/1398/commits/312939776745fa0545f6b4d1ba7c887655051c5b message: `s/dbus_close/dusb_close`

LGTM otherwise, thanks!

**Comment by jandryuk** [comment]
Updated with `s/dbus_close/dusb_close`.  Thanks to catching that.

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
