### PR TITLE
bbclasses: get makeclean to depend on force_rebuild

### PR DESCRIPTION
**Pull request by jean-edouard**
This will simplify working in OE.
It may not be the best way to implement it, please chime in if you know better.

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
I think there might be a couple of better ways to do this since there are plenty of packages that do incremental builds just fine and you may not want to do a full build (e.g. qemu that takes a while for a full build).

1. Add a new options like force_clean_rebuild that does both.
2. Switch it around and always make the makeclean option do a force_rebuild.

**Comment by jean-edouard** [comment]
I agree, I didn't think about that use case.
Your second suggestion makes a lot of sense, since `force_rebuild` brings the package back to the "configured" state, which is exactly what you would expect after a `makeclean`.
I'll switch the dependency around and see if it works.
Thanks

**Comment by jean-edouard** [comment]
Looking at the code again, "2." seems to be what I actually did.

**Comment by rossphilipson** [comment]
+1 - I am good with #2. I will leave it open for a bit for other comments...

**Pull request merged**
