### PR TITLE
STABLE-9: [upgrade] Build new 32-bit compat image to support

### PR DESCRIPTION
**Pull request by crogers1**
upgrades from 32-bit versions of OpenXT

  OXT-1539

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Updated PR to perfer the dummy linux image. This lowers the build time significantly because the upgrade-compat image doesn't actually need a real kernel built.

The other images correctly use "linux-openxt" when building, only upgrade-compat uses "linux-dummy".

**Comment by crogers1** [comment]
Fixed indent in image.bb

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6483

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6503
LGTM, merging soon, along with the other PRs included in the build:
https://github.com/OpenXT/xenclient-oe/pull/1124
https://github.com/OpenXT/openxt/pull/340
https://github.com/OpenXT/openxt/pull/341
https://github.com/OpenXT/installer/pull/100

**Pull request merged**
