### PR TITLE
Add VWIF support to libxl and Linux netback

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-973

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Depend on:
https://github.com/OpenXT/manager/pull/64
https://github.com/OpenXT/network/pull/5

**Comment by richpersaud** [comment]
Please reference a JIRA ticket that links related PRs, documenting the problem and solution.

**Comment by rossphilipson** [comment]
Built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/643

Testing now...

**Comment by jean-edouard** [comment]
Now depends on:
https://github.com/OpenXT/manager/pull/74
https://github.com/OpenXT/network/pull/8

**Comment by rossphilipson** [comment]
Tested, working. Merging soon.

**Pull request merged**
