### PR TITLE
Remove monit

### PR DESCRIPTION
**Pull request by eric-ch**
While monit could be useful in production for error recovery and resource starvation management, currently it is only restarting daemons in dom0 on failure which can hide (and
already has hidden) issues.

I understand this is debatable, as testing should be done on the daemons initialy and monit, only being a failsafe for now, could provide more help on resource based events and the likes. But, for now, I believe this is not used as such and can get in the way of development.

### CODE REVIEW

**Comment by rossphilipson** [comment]
+1 on this one too. Please create tickets for these.

**Comment by eric-ch** [comment]
@rossphilipson linked to OXT-514

**Comment by rossphilipson** [comment]
Some concerns were raised about removing this. Let's hold off until they are resolved.

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/25

**Comment by rossphilipson** [comment]
Will give it some testing on Monday.

**Comment by rossphilipson** [comment]
Testing a build with monit gone. Seems to be fine.

**Comment by rossphilipson** [comment]
Got clearance from concerned parties. Merging soon...

**Pull request merged**
