### PR TITLE
OXT-1581: keymgmt: Getenforce is not in the installer.

### PR DESCRIPTION
**Pull request by eric-ch**
On fresh installation:
```
stages/Install-fresh: line 1: getenforce: not found
+ [  == Enforcing ]
```

Install-fresh will source the key-functions to setup encryption.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6533

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Comment by jean-edouard** [comment]
@eric-ch stable-9 please

**Comment by dpsmith** [comment]
I am good with the fix, just a side question, should the recipe be made dependent to ensure selinux tools are installed?

**Comment by eric-ch** [comment]
@dpsmith This is used in both SELinux enabled and disabled images, maybe `RRECOMMENDS`? Not how much more than just the tools would be pulled in the image.

**Comment by eric-ch** [comment]
@jean-edouard https://github.com/OpenXT/xenclient-oe/pull/1161

**Pull request merged**
