### PR TITLE
OXT-1187: xen: upgrade to 4.6.6

### PR DESCRIPTION
**Pull request by eric-ch**
Remove upstream XSA backports.

See release notes:
https://www.xenproject.org/downloads/xen-archives/xen-46-series/xen-466.html

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [1019](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1019)

**Comment by eric-ch** [comment]
Depends on: https://github.com/OpenXT/openxt/pull/257

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1024

**Comment by eric-ch** [comment]
Force-pushed since the quiltrc did not match the existing formatting. This should reduce the diff noise.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1034

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
