### PR TITLE
Rewrite the linux-firmware recipe

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-977

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/708

**Comment by dozylynx** [comment]
@cjp256 : please could you review this PR?

**Comment by eric-ch** [comment]
+1 LGTM.

Firmwares are installed in dom0 and NDVM using build 708.

The recipe might as well only deal with the firmware used in OpenXT since it is duplicated from usptream until the OE recipe is upgraded.

**Comment by jean-edouard** [comment]
I don't have any, if you do and want to add it to the HCL, then just add your firmware to the recipe in a separate PR.

**Comment by dpsmith** [comment]
Just because none of us can test and put on the HCL doesn't mean we should allow the firmware of common cards to be included. By doing so, you have stopped end-users who might want to attempt and report back from doing so.

**Comment by jean-edouard** [comment]
Ok, sorry.

**Comment by dpsmith** [comment]
You didn't need to close the PR, wasn't trying to reject it. Like I said, I am for trimming down some of the firmware just don't exclude the more common devices.

**Comment by eric-ch** [comment]
In this case I believe the alternative is to send a PR upstream with the missing firmware and use the previous duplicated recipe with split packages in dom0 and NDVM in the mean time. This would radically modify the changes introduced by that PR.

**Comment by jean-edouard** [comment]
This PR adds firmware to the target, it doesn't remove any, but I don't have time to argue endlessly, I'll just diverge my downstream a bit more.

**Pull request closed without merging**
