### PR TITLE
STABLE-8: OXT-1352, OXT-1353: tapback, xcpmd: Fixes to initscript to use pidfiles.

### PR DESCRIPTION
**Pull request by eric-ch**
Use pidfiles to track daemons processes and stop them with `start-stop-daemon`.

### Related:
- https://github.com/OpenXT/blktap3/pull/8
- https://github.com/OpenXT/xctools/pull/46

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1568

**Comment by rneilturner** [comment]
I ran into an issue with the blktap commit. I get an XL exception when starting the UIVM and the VM immediately gets destroyed. Are you seeing this issue?

**Comment by eric-ch** [comment]
@rneilturner Done.

**Comment by rneilturner** [comment]
Tested and looks good.

**Comment by eric-ch** [comment]
Build: [$1590](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1590)

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
