### PR TITLE
OXT-352 Enable gntdev module in the uivm and stubdomain kernel configs

### PR DESCRIPTION
**Pull request by brendank310**
Signed-off-by: Brendan Kerrigan <kerriganb@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
+1

**Comment by eric-ch** [comment]
+1

**Comment by jean-edouard** [comment]
A ticket was requested on the mailing list, and created in Jira.
I'm assuming this is now safe to merge. Will do so tomorrow morning if there's no further objection.

**Comment by transpute** [comment]
Can the ticket number be added to the PR, so this commit is linked to the the ticket?

**Comment by jean-edouard** [comment]
https://openxt.atlassian.net/browse/OXT-352

**Comment by transpute** [comment]
For th github <-> JIRA integration plugin, the ticket number may need to be in the title.

**Comment by jean-edouard** [comment]
Good now?

**Comment by transpute** [comment]
Yes, the PR now shows up in the JIRA ticket, thanks.

+1 on merge

**Pull request merged**
