### PR TITLE
linux: revert 2 commits that force console output to the screen

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6487

**Comment by jean-edouard** [comment]
Note: this a less-than-ideal way of fixing the problem. I'll gladly close this if a better fix gets PR-ed.

**Comment by jandryuk** [comment]
I tried a non-EFI boot adding "quiet loglevel=0" to the linux command line.  That seems to remove all the messages.

**Comment by eric-ch** [comment]
@jandryuk That will silence the output entirely, which is not what this PR means to do. The reverted commits forced the output on `tty0` (current console) which will end up on the installer display (tty1 I presume). It was not the case before when specifying `tty2` on the cmdline.

**Comment by jandryuk** [comment]
I thought this PR was trying to reduce boot output during a normal boot as opposed to the installer since that changed with the 4.19 uprev.  @jean-edouard what are you trying to achieve here?

**Comment by jean-edouard** [comment]
As @eric-ch said, the point is to avoid to logs to be shown on screen at boot time. But we do want them in dmesg/syslog. This is purely cosmetic.

**Comment by jandryuk** [comment]
With "quiet loglevel=0", dmesg still has the messages and syslog picks them up and writes them to /var/log/messages - they just don't appear on the display.

**Comment by jean-edouard** [comment]
@jandryuk oh interesting, I thought that would have limited the actual logs we get from the kernel / modules. Will test.

**Comment by eric-ch** [comment]
@jandryuk (I got confused and thought of the installer spurious logs, this is for initial console output at boot time)

`quiet loglevel=0` will shutdown the serial log output as well as the default console.

**Comment by jandryuk** [comment]
Oh, that's unfortunate that it stops serial console output.  I had not checked that.

**Comment by eric-ch** [comment]
I am surprised these original patches did not use `console_set_on_cmdline` to avoid overriding cmdline configuration. Not that it was checked before either though. Would that make sense?

**Comment by jandryuk** [comment]
I wasn't aware of console_set_on_cmdline, but it looks like it might be usable.  Provided the cmdline is parsed...  That doesn't look promising.

The add_preferred_console calls are in xen_start_kernel
xen_start_kernel
  x86_64_start_reservations
    start_kernel
      setup_arch - this is where it grabs the command line.

I think the above is correct - I haven't found where it is parsed.

Xen ARM has:
```
        if (!console_set_on_cmdline && !xen_initial_domain())
                add_preferred_console("hvc", 0, NULL);
```
But that may come after the command line is parsed.

**Comment by eric-ch** [comment]
Build [$6507](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6507)

**Comment by eric-ch** [comment]
@jandryuk Right, the cmdline is not parsed yet, so `console_set_on_cmdline` is not ready.

This change only affected dom0, do you think it is preferable to add a single patch removing the `add_preferred_console("tty", 0, NULL);`, putting it back under `if (!xen_initial_domain())`, as a temporary solution instead of reverting upstream changes?

**Comment by jandryuk** [comment]
For the time being, the simplest thing may be just to add a patch commenting out the tty lines.  With a nice patch description stating exactly why we are doing this.

The proper fix would probably be to delay `add_preferred_console` calls until after the command line is parsed so the entire code block can be placed under `if (!console_set_on_cmdline)`.  Provided x86 actually parses the command line before enabling the regular consoles...

**Comment by eric-ch** [comment]
Without the reverts: https://github.com/OpenXT/xenclient-oe/pull/1126

**Pull request closed without merging**
