### PR TITLE
STABLE-8: [xl] Use sigsuspend to synch xenmgr and xl domain

### PR DESCRIPTION
**Pull request by crogers1**
reboot.  Remove old reboot fix patch

  OXT-1299

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [$1508](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1508)

**Comment by eric-ch** [comment]
Can you please refresh your patch with the [configuration provided on the wiki](https://openxt.atlassian.net/wiki/spaces/DC/pages/20905986/Dealing+with+quilt) please?

**Comment by crogers1** [comment]
Yea I can do that tomorrow

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1525

**Comment by jean-edouard** [comment]
LGTM, will merge after refresh.

**Comment by jean-edouard** [comment]
Along with https://github.com/OpenXT/manager/pull/115

**Comment by crogers1** [comment]
Updated with quilt style.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1534

**Pull request merged**
