### PR TITLE
Add the 20190312 and 20190514 microcode.

### PR DESCRIPTION
**Pull request by rneilturner**
Signed-off-by: Richard Turner <turnerr@ainfosec.com>

OXT-1605

### CODE REVIEW

**Comment by jandryuk** [comment]
Hi, @rneilturner does this 20190312 release provide the MDS/MD_CLEAR support?  https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files has a 20190514 (and 20190514a) release.  The actual microcode date on a Kaby Lake processor is 2019-04-01 (for microcode-20190514).  20190514 has the MDS mitigations.

**Comment by rneilturner** [comment]
> Hi, @rneilturner does this 20190312 release provide the MDS/MD_CLEAR support? https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files has a 20190514 (and 20190514a) release. The actual microcode date on a Kaby Lake processor is 2019-04-01 (for microcode-20190514). 20190514 has the MDS mitigations.

Thanks @jandryuk , It would help if I had the 20190514a commit as well. Posting soon.

**Comment by rneilturner** [comment]
We are still doing on-going testing for 20190514. I will post any problems we run into as we continue our testing.

**Comment by eric-ch** [comment]
Build [$6566](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6566)

**Comment by rneilturner** [comment]
Added the 20190514a microcode.

**Comment by eric-ch** [comment]
Keeping the previous release around for testing is fine IMHO.
Currently this microcode is only in `meta-intel` `master` branch, so the modifications are according to the new packaging of the tarball

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
