### PR TITLE
libxl: fix PCI passthrough with stubdoms

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-894

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
+1 looks good.

**Comment by richpersaud** [comment]
Can we upstream this to Xen?

**Comment by jean-edouard** [comment]
Define "we", define "can" :)
This is definitely "upstreamable" if that's the question.

**Comment by jean-edouard** [comment]
Please hold off on merging, I'm missing a case.

**Comment by jean-edouard** [comment]
Fixed, sorry I had to force-push, please re-review.

**Comment by eric-ch** [comment]
LGTM

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/566

**Comment by jean-edouard** [comment]
I fixed the conflict here to avoid a force-push: https://github.com/OpenXT/xenclient-oe/pull/535

**Comment by rossphilipson** [comment]
Built here, testing now:
http://openxt.ainfosec.com/builds/custom/master/587/

**Comment by rossphilipson** [comment]
Tested GPU PT of an AMD card worked fine. Merging soon.

**Comment by rossphilipson** [comment]
Ok so another one of these is open. I guess we will abandon this one...

**Pull request closed without merging**
