### PR TITLE
OXT-1445: QEMU 3.0

### PR DESCRIPTION
**Pull request by jandryuk**
This uprevs to QEMU 3.0.  Changes are pretty straightforward, but two notable items.

libxl is [changed](https://github.com/OpenXT/xenclient-oe/commit/f1412cfa16d84650ffb8a1db2143737926ec6a63) to leave cdroms as format=host_cdrom to avoid this warning:

> warning:  Opening a block device as a file using the 'file' driver is deprecated

@jean-edouard I think you introduced the patch to set format=file.  Changing ISO images works, but I'm not sure why this patch was originally introduced.  Do you think this is okay?

atapi passthrough is untested, so testing is appreciated.

### CODE REVIEW

**Comment by jean-edouard** [comment]
@jandryuk, the format=file thing was probably to replicate xenvm's behavior. Removing that patch is probably fine.
Cool upgrade, I'll kick a build!

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1747
Is it just me or is it much slower than 2.6.2? (Win10 64b guest)

**Comment by jandryuk** [comment]
I can't say I paid attention or noticed a speed change.

I tested Windows 7.  I didn't have a tools CD, so it starts off empty with the null.iso.  I then puts some ISOs in /storage/isos.  They didn't show up immediately in the VM's hardware tab, but entering and exiting Install VM got them to showed up.  Changing ISOs changed the virtual CD.  I'll check out Windows 10.

**Comment by jandryuk** [comment]
Selecting ISOs in my Win10 vhd works as well.

**Comment by jandryuk** [comment]
I reproduced on build 1747.  Initial boot with a specified ISO doesn't show up as virtual CD.  Switching after boot exposes the ISO.

**Comment by jandryuk** [comment]
Seems to be something with format=host_cdrom - format=host_device detects the already-inserted ISO at boot.  I haven't nailed down why, but it seems host_cdrom tries to inspect the device likes it's a real cdrom.  xen block front devices only have limited emulation of a cdrom, so host_device may be a more appropriate format specification.

**Comment by jandryuk** [comment]
Force-pushed new libxl patches.  The first uses host_device and consolidates some of the stubdom disk patching.  With that, the second redoes the patch queue refresh.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1758

**Comment by jean-edouard** [comment]
Emulated CDs work fine now, but I noticed another issue: when a VM is restarted it loses focus and the user has to manually switch back to it.

**Comment by jandryuk** [comment]
Okay, thanks for testing.  I'll take a look.

**Comment by richpersaud** [comment]
@jandryuk will upstream Xen (targeted for 4.12) patches for Linux stubdoms allow us to reduce the OpenXT patch queue?

**Comment by jandryuk** [comment]
Going off memory, I think these patches will all go away with upstreamed linux stubdom support:
libxl-RFC-4of7-Add-stubdomain-version-tools-domain-build-info.patch
libxl-RFC-5of7-Handle-Linux-stubdomain-specific-QEMUoptions.patch
libxl-RFC-6of7-Build-the-domain-with-a-Linux-based-stubdomain.patch
libxl-RFC-7of7-Wait-for-QEMU-startup-in-stubdomain.patch
libxl-linux-stubdom-replace-disk-with-initramfs.patch
libxl-RFC-fix-multiple-disks.patch

Naturally other patches will probably need a little re-working.

**Comment by eric-ch** [comment]
Building: [$1770](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1770)

**Comment by eric-ch** [comment]
Building [$1772](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1772)

**Comment by eric-ch** [comment]
Will merge soon.

**Comment by eric-ch** [comment]
Build [$1776](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1776)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1782

**Pull request merged**
