### PR TITLE
ZEUS: layer/zeus: fix sub-project versions

### PR DESCRIPTION
**Pull request by eric-ch**
Fix the revisions of sub-project to their stable version for this layer stable branch.

In order to simplify version management, since multiple recipes can pull a common repository, move the source/revision configuration to a matching include file and sort the recipes per repository provider.

The current revisions are the tips of the master branches for each subprojects.

Should the need for numbered version management per subproject arise, it is now a matter of changing the relevant .inc file and submitting a PR against this branch.

### CODE REVIEW

**Comment by dpsmith** [comment]
Looks good to me, probably good to let the public builder run through it to make sure it will result in install-able build.

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/3/builds/20): [$zeus-stable-20](https://openxt.ainfosec.com/OpenXT/auto/zeus/zeus-stable/20/)

**Review by jandryuk — APPROVED** [review]

**Comment by jandryuk** [comment]
I'm okay with merging this.  Do we want to coordinate with master so that the files paths are kept in sync?  Or just put this one in now and fix up master later?

**Comment by eric-ch** [comment]
@jandryuk I think we should forward-port the recipe path changes into master. It might be worth doing after the Dunfell upgrade gets in to minimize conflicts.

**Comment by jandryuk** [comment]
Ok.  Will merge soon.

**Pull request merged**
