### PR TITLE
OXT-1011 Fixes

### PR DESCRIPTION
**Pull request by jean-edouard**
Merge of https://github.com/OpenXT/xenclient-oe/pull/603 and https://github.com/OpenXT/xenclient-oe/pull/591

### CODE REVIEW

**Comment by rossphilipson** [comment]
Started a build for this (10th try) here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/786
We can close out 603 and 591 I think.

**Comment by rossphilipson** [comment]
Associated PRs:
https://github.com/OpenXT/network/pull/10
https://github.com/OpenXT/manager/pull/78
https://github.com/OpenXT/idl/pull/27

**Comment by rossphilipson** [comment]
See tickets for latest test results. I am fine with these 4 being merged even though I think there are some problems still outstanding. They clearly make things much better.

I know we said we were freezing until we branched but I would +1 getting this in and letting people know via the ML. These have been outstanding for a long time.

**Comment by richpersaud** [comment]
Do we expect this PR to improve the stability of networking or the overall system, or are the changes targeted only at the specific issues listed in OXT-1011?

**Pull request merged**
