### PR TITLE
Update XSA patches from XSA-123

### PR DESCRIPTION
**Pull request by eric-ch**
Update XSA patches in both Xen and QEMU patch-queues.

Only applies XSA after XSA-123 as Xen 4.3.4 is already including the other (exception being of XSA-59, still in the patch-queue).

Also add some renaming scheme to make things a little bit less confusing for our patch-queues and include source links and small documentation using the patch header format used in other OpenXT patch-queues.

### CODE REVIEW

**Comment by cjp256** [comment]
Nice job!  I like the organization.

@jean-edouard if you can kick off a build, I'll give it a test run when it is ready.

**Comment by jean-edouard** [comment]
http://openxt.ainfosec.com:8020/builders/extbuilder/builds/319

**Comment by cjp256** [comment]
@jean-edouard thanks!

**Comment by jean-edouard** [comment]
Looks all good to me... VMs start with or without stubdoms.
I guess you backported xsa-137 and xsa-142 in prevision of an eventual toolstack upgrade, I like your optimism :)
+1, will merge soon.

**Comment by transpute** [comment]
For tracking purposes, we should have a JIRA ticket for non-optional security fixes, so we can track which branches have the fixes.  

Does anyone plan to backport this to stable4?

**Comment by jean-edouard** [comment]
@transpute could you maybe create a draft for the Jira ticket? I could work with Eric on filling the blanks.

I don't know of any plan to backport those to stable4, no.

**Comment by jean-edouard** [comment]
@transpute are you against merging this before the Jira ticket happens?
I'd like to merge the PR before it breaks (not like https://github.com/OpenXT/xenclient-oe/pull/176)

**Comment by transpute** [comment]
No objection to merge. 

JIRA ticket would provide metadata for later queries, so we know which security patches are in which branches.

**Pull request merged**
