### PR TITLE
[tpm2-tools] Fixup project name in srcuri

### PR DESCRIPTION
**Pull request by crogers1**
and patches for the tpm2 projects.

Signed-off-by: Chris <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Upstream changed their repository names so our fetches are going to fail unless we update.

**Comment by jean-edouard** [comment]
Failed to build: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1055/steps/Build/logs/stdio

**Comment by eric-ch** [comment]
Building [#1081](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1081)

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
