### PR TITLE
Remove Haskell platform components to meta-openxt-haskell-platform

### PR DESCRIPTION
**Pull request by dozylynx**
OXT-792: Transfer Haskell platform components to meta-openxt-haskell-platform repository.

This PR will require a corresponding PR for meta-openxt-haskell-platform.git and a new layer definition file for openxt.git. It will affect build sites due to the need to clone the new haskell repository into place for future builds.

Signed-off-by: Christopher Clark christopher.clark6@baesystems.com

### CODE REVIEW

**Comment by dozylynx** [comment]
It would be helpful to coordinate any merge of this with me, please, since it is disruptive to existing build environments and we should communicate this properly to the community beforehand. There will also be a similar change for the OCaml layer and it would be sensible to do both at the same time.

**Comment by dozylynx** [comment]
PR refreshed with rebase onto current tip of master, accounting for two relevant commits:
16c2ece05c8af324e74af5b96d3670d668a80531 and 9b330344b0771647d7bd4f5161738b32229d5704

**Comment by dpsmith** [comment]
lgtm

merging soon

**Comment by jean-edouard** [comment]
Hmm, did you test this?

**Comment by dpsmith** [comment]
Yes, but you are welcome to do your own build to test as well.

**Comment by dozylynx** [comment]
@jean-edouard : do you have any specific concern or understanding of this change that you'd like to share?

**Comment by jean-edouard** [comment]
It's just that we usually test PRs before merging them...

**Pull request merged**
