### PR TITLE
OXT-1629: [sqlite3] Upgrade sqlite3 and pseudo

### PR DESCRIPTION
**Pull request by crogers1**
The pseudo upgrade is required because 1.8.2 can't build
  against sqlite3 3.29.0. 3.29.0 gets us the latest CVEs.

  OXT-1629

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6668

**Comment by jean-edouard** [comment]
That seems slightly overkill... Do we actually use sqlite in OpenXT (outside of the build system)? I see just libsqlite installed as a dependency of nss, but maybe nss can be built without it?

**Comment by eric-ch** [comment]
Build ($6691)[http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6691]

**Comment by crogers1** [comment]
@jean-edouard do you still want me to see if we can build nss without libsqlite, or will we take this as is?

**Comment by jean-edouard** [comment]
@crogers1 the former. I can investigate if you'd like, let me know.
This PR is "linked" to https://github.com/OpenXT/xenclient-oe/pull/1212, right?

**Comment by jean-edouard** [comment]
nss can't be built without sqlite... It can build its own libsqlite, but it has the same name/path as the standalone one, which leads to conflicts.

**Comment by crogers1** [comment]
Interesting.  Thanks for checking that. And yes it's linked to #1212

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
