### PR TITLE
[qemu-dm] add a compile-time option for stubdomains

### PR DESCRIPTION
**Pull request by jean-edouard**
The code comes directly from https://github.com/OpenXT/xenclient-oe/pull/80.

Signed-off-by: Brendan Kerrigan <kerriganb@ainfosec.com>
Signed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rianquinn** [comment]
The patch should probably be applied to the beginning, not the end of the patch queue. This way, previous patches can also leverage it if needed. Other than that, it looks good.

**Comment by jean-edouard** [comment]
I agree, I thought about it but didn't want to rebase the other patches on top...
I guess I'll do it then.

**Comment by rianquinn** [comment]
:smile:

**Comment by jean-edouard** [comment]
Here you go, enjoy!

**Comment by brendank310** [comment]
LGTM, thanks for separating it out.  I'll build it, but my build tree is clean so it's a full rebuild for me. I think it's an innocuous enough change to just merge in.

**Comment by rossphilipson** [comment]
I looked it over too. It is ugly but that is the cost of moving it to the bottom. Merging.

**Pull request merged**
