### PR TITLE
Add rtglobal scheduler

### PR DESCRIPTION
**Pull request by Ashughorla**
We need an RT Scheduler in OpenXT environment. For this we have ported the patches from 
https://sites.google.com/site/realtimexen/rt-openstack into the xen-4.3.4 used in the xenclient-oe interface.

Please review and merge.

Thanks,
Ashu.

### CODE REVIEW

**Comment by transpute** [comment]
Thanks for sharing this scheduler port.

I will let others provide feedback on the structure of files in this PR.  We may need to update the Contribution Guidelines (https://github.com/OpenXT/openxt/wiki/Contributing) with a note about the undesirability of patch files within recipes.

After looking at http://www.mrtc.mdh.se/vtres2013/VtRES_2013_keynote.pdf and http://www.cse.wustl.edu/%7Elu/papers/cloud15-rtopenstack.pdf, I think this new feature would benefit from an RFC (https://github.com/OpenXT/openxt/wiki/RFC-Submission) discussion on the mailing list.  

Some questions which could be addressed in the RFC:

- Is the use case single embedded servers (planes, trains, autos, ships, industrial control) which are configured once and then run standalone, or is the use case a group of "cloud" servers with local-only storage and remote management by OpenStack?

- How should this feature be integrated into the existing OpenXT toolstack?  Alternately, how can another toolstack be safely/reliably/correctly run in parallel with the existing xenvm/XenMgr toolstack?

- What are instructions for testing the new scheduler?

- Are you a member of the RT-OpenStack dev/research community? Will RT-OpenStack patches be upstreamed to other projects?  Until then, is the RT-OpenStack code actively maintained?  If so, who will keep the OpenXT version synchronized with the code.google repo?  Are there plans to move the RT-OpenStack work to github?

**Comment by rossphilipson** [comment]
I agree with @transpute that more discussions are needed around this.

I have a technical question though. This is the RT-Xen 2.1 version of the scheduler mentioned in http://www.cse.wustl.edu/%7Elu/papers/cloud15-rtopenstack.pdf - correct? How does this relate to the RTDS that is now part of Xen 4.5/4.6?

**Comment by lchandivade** [comment]
The RTDS is similar except it does not have a provision to indicate if a dom is rt (real-time) or not. Based on the type rt or non-rt the rtglobal applies  EDF to rt doms and round-robin to non-rt doms.

Are there plans to get Xen 4.5.1 or higher into OpenXT?

**Comment by rianquinn** [comment]
Yes, we are in the initial stages of moving to 4.6. Our goal was to work on incorporating RTDS as we would like to stay inline with upstream as much as possible.

**Comment by rossphilipson** [comment]
So is this something that could be up-streamed in Xen as the next version of RTDS? Maybe it would be better to try to get it in there and we could easily pick it up when we move to something closer like 4.6? Just an idea; maybe it makes sense to have it here too.

I spoke to Meng Xu at Xen Summit for a bit. I guess it wasn't clear to me how this version (RT-Xen 2.1) fit in with what he and others were planning for the next version of RTDS. Maybe we should schedule a call for those interested or discuss this at our next community call (which is in October I believe).

**Comment by rossphilipson** [comment]
Ping. Any feedback on this? We would like to discuss this further.

**Comment by lchandivade** [comment]
It would be good to get the 4.6 in openxt. That will give us the RTDS and eventually have the RT-Xen 2.1 integrated upstream into xen.

**Comment by transpute** [comment]
@lchandivade It could be as long as a year before the move to Xen 4.6.  Are you available for discussion on the list or in the December community conference call?

**Comment by lchandivade** [comment]
No, my team is not working actively on getting RT-Xen 2.1 to upstream. 

Also some other points that need attention
- xl integration is also needed to update scheduler parameters. Current tools like xec-vm/xenops did not work for us. 
- By default credit scheduler is selected. Toolstack would need updates to allow booting OpenXT with other schedulers. We ran into this issue, discussed at
https://groups.google.com/forum/#!topic/openxt/-jVRl45IvRg

I am not active on the list, however do let me know if any discussion is needed.

**Comment by jean-edouard** [comment]
This PR seems to need more discussion, and it can't be merged anyway because of conflicts.
It was also submitted before the Jethro merge, so it would need to be re-tested.

@lchandivade, please close this PR, it can easily be re-opened once the conflicts are fixed and the community is in agreement for getting it in.

**Comment by jean-edouard** [comment]
Stale, closing...

**Comment by richpersaud** [comment]
@Ashughorla @lchandivade now that OpenXT has integrated xl and Xen 4.9, are you still interested in an RT scheduler for OpenXT?

**Pull request closed without merging**
