### PR TITLE
OXT-1051: linux-openxt: micro-upgrade to 4.9.20

### PR DESCRIPTION
**Pull request by eric-ch**
Amongst everything:
xen: do not re-use pirq number cached in pci device msi msg data

OXT-1051

### CODE REVIEW

**Comment by geoncoder** [comment]
Where is the bb recipe changes for this PR?

**Comment by eric-ch** [comment]
@geoncoder ... missing. The new commit has it. My apologies for the inconvenience.

**Comment by rneilturner** [comment]
+1 installed and looks good

**Comment by rossphilipson** [comment]
Great thanks. Will merge with RM signoff.

**Comment by dpsmith** [comment]
reviewed-by: dpsmith@apertussolutions.com

**Pull request merged**
