### PR TITLE
OXT-664: Update OpenSSL to 1.0.1t

### PR DESCRIPTION
**Pull request by dozylynx**
Fixes CVEs.

Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Any thoughts on testing this?

**Comment by dozylynx** [comment]
Fair question.
I think we need to identify what components of ours are using SSL, which would be useful to know anyway. I think the browser in the UIVM is has a dependency on libssl, but I don't know whether we use https transport for our UI, so we might have to coerce it into connecting to an external https site to test it.

OpenSSL can be driven as a command line tool. That's a reasonable way to smoke test that it has at least built a plausible binary.

**Comment by eric-ch** [comment]
It seems reasonable to assume that upgrading openssl micro should be safe.
I recommend we merge this one and have it tested during the RC process since we have no specific test. Testing the RC should provide a good enough coverage regarding the changes involved until someone figures out a better way.

**Comment by rossphilipson** [comment]
@eric-ch I like you suggestion, +1

**Comment by jean-edouard** [comment]
+1, @dozylynx we probably want that in stable-6 too?

**Comment by rossphilipson** [comment]
Yea we are ready to do the RC build, we need to get this in.

**Comment by jean-edouard** [comment]
I created the stable-6 PR, hope you don't mind @dozylynx!

**Comment by rossphilipson** [comment]
Will merge soon.

**Pull request merged**
