### PR TITLE
install-bootloader: fix partition-to-disk resolution

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-454

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/75

**Comment by jean-edouard** [comment]
Needs https://github.com/OpenXT/installer/pull/16

**Comment by jean-edouard** [comment]
Successfully tested on both SCSI and NVMe.

**Comment by rossphilipson** [comment]
Was involved with this with @jean-edouard when he was fixing it and saw it tested successfully. Will merge soon.

**Pull request merged**
