### PR TITLE
libxl: fix network-detach

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1011

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Build here http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/746

**Comment by rossphilipson** [comment]
Testing...

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/754

**Comment by eric-ch** [comment]
With https://github.com/OpenXT/xenclient-oe/pull/609 handling the rebase of https://github.com/OpenXT/xenclient-oe/pull/603 and https://github.com/OpenXT/xenclient-oe/pull/591, this PR should be closed.

**Pull request closed without merging**
