### PR TITLE
openssl: update to 1.0.1m to address CVEs

### PR DESCRIPTION
**Pull request by cjp256**
This update has been pulled directly from OE-core @
8e46230fe94c44ab81a0ca9cb8b2c9f7b605e226

Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

### CODE REVIEW

**Comment by cjp256** [comment]
Built, but untested.  Just putting this out there for review while I work on testing it.

**Comment by cjp256** [comment]
Tested.  Encrypted disks seem to work fine, syncvm still syncs.

**Comment by jean-edouard** [comment]
Where do you define ${PTEST_PATH}?
Why do you remove -DTERMIO? Did you try "TERMIOS"?

**Comment by cjp256** [comment]
I didn't remove/change anything, I yanked it from oe-core (rm -rf on old openssl, and cp -r new one) for the first commit.  Then I dropped the ptest bits as they use a ptest class that doesn't exist in our current OE tree.

**Comment by cjp256** [comment]
I might have the commit hash wrong in the commit message, I believe the top most commit was:
http://git.openembedded.org/openembedded-core/commit/?h=daisy&id=a2966949e68bbdce8d0a0fd5946d078b84ae63e9

**Comment by jean-edouard** [comment]
Oh I missed your second commit, sorry!
LGTM then.

**Pull request merged**
