### PR TITLE
tpm-functions: use dmesg instead of not-always-there sys node to detect TPM 2.0

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Jed we're going to be submitting a PR soon with an alternative approach that still queries the sysfs device, but handles the general case better, I recommend taking a look at that.  

I don't think this PR is a bad way of checking for TPM version, but the dmesg buffer could empty.  Asking the sysfs device, in my mind, will be more reliable.

**Comment by jean-edouard** [comment]
Thanks for the info @crogers1, I guess we should hold off the merge then.
For the record, this PR is built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1436

**Comment by crogers1** [comment]
@jean-edouard no problem.  The engineer working this is out today, I can make sure he pushes it first thing Monday

**Comment by eric-ch** [comment]
@crogers1 Any news?

**Comment by crogers1** [comment]
I believe Rich will be posting a PR soon.

**Comment by eric-ch** [comment]
https://github.com/OpenXT/xenclient-oe/pull/879 got merged. This PR can now be closed.

**Pull request closed without merging**
