### PR TITLE
VM templates: un-duplicate

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Goes with: https://github.com/OpenXT/manager/pull/22

**Comment by rossphilipson** [comment]
Ticket number?

**Comment by jean-edouard** [comment]
OXT-532

**Comment by rossphilipson** [comment]
I will build and test an install before merging.

**Comment by rossphilipson** [comment]
Tested, looks good. Will merge soon.

**Pull request merged**
