### PR TITLE
OXT-1306: OXT-1732: drop dbus argo.patch

### PR DESCRIPTION
**Pull request by jandryuk**
This PR changes syncvm to no longer use family=argo in DBUS_SYSTEM_BUS_ADDRESS.  argo.patch is then removed from dbus.  Also, the dbus DEPENDS are cleaned up to just use meta-selinux's .bbappend.

This PR depends on https://github.com/OpenXT/sync-client/pull/5 since INET_IS_ARGO is set for sync-client after these changes.

OXT-1306
OXT-1732

### CODE REVIEW

**Comment by jandryuk** [comment]
bvt would need to change https://github.com/OpenXT/bvt/blob/be34216d950661ea0f49972322a967862c23d6d0/src/testcases/syncxt_test.py#L447 and add INET_IS_ARGO=1 to https://github.com/OpenXT/bvt/blob/be34216d950661ea0f49972322a967862c23d6d0/src/testcases/syncxt_test.py#L456
But that repo seems dead, so maybe we should archive it?

**Comment by eric-ch** [comment]
Build [$10039](http://openxt-builder.ainfosec.com:8010/#/builders/3/builds/10039)

**Comment by eric-ch** [comment]
> But that repo seems dead, so maybe we should archive it?

Defunct repositories used to be moved to https://github.com/OpenXT-extras. That one looks like a candidate.

**Comment by stacktrust** [comment]
Add ticket number OXT-1306 to this and related PRs?  Or we can change the description of OXT-1732.

Archiving BVT sounds good.

**Comment by jandryuk** [comment]
The ticket numbers are in the relevant commit messages.

**Comment by stacktrust** [comment]
I don't think JIRA can auto-connect this PR to the tickets, without having the ticket numbers in the PR description:  https://openxt.atlassian.net/browse/OXT-1732

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
