### PR TITLE
OXT-1421: XSA-270 Linux netback driver OOB access in hash handling 

### PR DESCRIPTION
**Pull request by jandryuk**
https://xenbits.xen.org/xsa/advisory-270.html

This is not upstream yet.

OXT-1421

This is on top of https://github.com/OpenXT/xenclient-oe/pull/1031.  Once that is merged, it is just a single commit.

### CODE REVIEW

**Comment by jean-edouard** [comment]
@jandryuk, in my experience, stacking PRs doesn't work on github. I don't think merging #1031 will reduce this one to 1 commit.

**Comment by jandryuk** [comment]
@jean-edouard I'm curious what will happen after #1031 is merged.  If it still shows all the commits, I'll rebase.  Merging this branch and #1031 should produce the same end result...

**Comment by jean-edouard** [comment]
Yeah, I'm curious too, we'll see but I won't merge this one if it still shows many commits, because I'm pretty sure that will generate a big merging mess in the history.

**Comment by jean-edouard** [comment]
@jandryuk, see? :)

**Comment by eric-ch** [comment]
@jandryuk Thanks for the backport. I am currently holding off a PR to upgrade Xen 4.10 and backport the recent XSA to avoid conflicts with https://github.com/OpenXT/xenclient-oe/pull/890

**Comment by eric-ch** [comment]
Building [$1732](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1732)

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
