### PR TITLE
Allow writable CDs and fix guest crash on write.

### PR DESCRIPTION
**Pull request by rossphilipson**
This fixes CD writing to what it is in stable-6 currently. Some things fail
like formatting the CD or dragging files/burning. Other things work like
right clicking an ISO and burning it to a CD. A separate ticket will be
opened to track those failures but this fixes the RO problem and the crash.

OXT-931

Signed-off-by: Ross Philipson <philipsonr@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Build here http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/746

**Comment by eric-ch** [comment]
Tested build with win7 & win10 guests on a Dell 9020, with and without stub-domain:
- No crash, but...
- Trying to read the disk triggers "An error occured while ejecting 'DVD RW Driver (D:)'
Could not read or write to the disk.

**Comment by rossphilipson** [comment]
Also built here with just the CD fixes:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/744

**Comment by rossphilipson** [comment]
I just tested 744 on my HP EliteDesk 800 G1 SFF and I was able to burn an ISO to the disk (with SELinux on and off) then read it.

**Comment by cjp256** [comment]
LGTM

**Comment by rossphilipson** [comment]
Just burned and then read an ISO on a Dell E6540 laptop with 744 without problems.

**Comment by cjp256** [comment]
LGTM, ATAPI PT has been known to be flaky at times anyhow :)

**Pull request merged**
