### PR TITLE
xenstored: enable core dumps to help diagnose crashes

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Depends on https://github.com/OpenXT/xenclient-oe/pull/644

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/876

**Comment by dpsmith** [comment]
I have reviewed the changes, if you want to do a PR against stable-7 branch, then I will sign off and we can get this into 7.0 to help catch the xenstore crash.

**Comment by rossphilipson** [comment]
LGTM merging soon

**Pull request merged**
