### PR TITLE
[xen] fix leaks and formatting in v4v firewalls

### PR DESCRIPTION
**Pull request by jean-edouard**
Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by cjp256** [comment]
LGTM

**Comment by cjp256** [comment]
Noted that this is missing signoff (and ticket?).  Any test steps?

**Comment by jean-edouard** [comment]
No ticket nor repro steps, this was found by looking at the code.
A possible issue would be that VMs can't shutdown after getting an XSM/viptables denial, as the denials would increment (and not decrement) the refcount on the domain. Also a big amount of denials could lead to a visible memory leak.

**Comment by cjp256** [comment]
Testing looks good to me.

**Pull request merged**
