### PR TITLE
libxl: do not wait for nic backend nodes to disappear, they wont

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1049

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Build here http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/746

**Comment by rossphilipson** [comment]
Testing...

**Comment by rossphilipson** [comment]
I need more information on how to test this - see ticket.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/754

**Comment by rossphilipson** [comment]
Ok tested (details in ticket), looks good. Will merge after RM signoff.

**Pull request merged**
