### PR TITLE
file: use release tarball instead of git

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1021

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Since the build is currently broken and this fixes it I am going to merge it very soon.

**Comment by dpsmith** [comment]
Would it not be better to just update the hash like OE upstream has done?[1](http://git.openembedded.org/openembedded-core/commit/?h=krogoth&id=b35225c88ff681a4a903f7fb4612ac768214f539).

**Comment by jean-edouard** [comment]
I'm not sure I see the point of using a hash, and it'll likely break again!

**Comment by jean-edouard** [comment]
(This is how I found the release tarball: https://github.com/file/file -> http://www.darwinsys.com/file/ -> ftp://ftp.astron.com/pub/file/)

**Comment by dpsmith** [comment]
As long as we have provenance and are willing to maintain.

**Comment by rossphilipson** [comment]
So what is the final story on this? We need to unbreak the build.

**Comment by dpsmith** [comment]
Pull it

**Comment by rossphilipson** [comment]
Ack, merging.

**Pull request merged**
