### PR TITLE
refpolicy: fix some tapdisk AVCs

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
All the credit for this goes to @stephensmalley, who decrypted the AVCs and suggested solutions.
Will PR against stable-8 if testing goes well.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1452

**Comment by jean-edouard** [comment]
Sorry, force-pushed to fix a typo and add firsboot_t fds.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1455

**Comment by eric-ch** [comment]
Will merge soon.

**Comment by eric-ch** [comment]
Will merge soon.

**Comment by eric-ch** [comment]
@jean-edouard Can you PR against stalbe-8 please?

**Pull request merged**
