### PR TITLE
OXT-580: Updated mobile-broadband-provider-info and syslinux to use u…

### PR DESCRIPTION
**Pull request by eric-ch**
…pstream OE.

syslinux was converted into a bbappend file that only has the couple of differences we have so we are mostly dependant on OE now.

mobile-broadband-provider-info was converted into a bbappend.

Initial PR: https://github.com/OpenXT/xenclient-oe/pull/546

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [745](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/745)
Introduces 1 new warning:
```
tmp-glibc/work/xenclient_uivm-oe-linux/xenclient-uivm-image/1.0-r0/temp/log.do_rootfs:WARNING: The license listed CCPD was not in the licenses collected for recipe mobile-broadband-provider-info
```

**Comment by eric-ch** [comment]
The initial recipe looks quite old. Since this is in the scope of OXT-580, we might as well take the opportunity to use the upstream one directly, upgrading in the mean time.

The version management quirk is handled by bitbake/OE anyway and the LICENSE in the upstream recipe is correct, so no warning. The most recent tag is 20170310 in the project's repo. If need be, another ticket/PR can take care of that upgrade using a new .bbappend.

**Comment by eric-ch** [comment]
The syslinux upgrade breaks the installer (missing ldlinux.c32). Will re-open when fixed.

**Comment by eric-ch** [comment]
Building: [873](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/873)

**Comment by rossphilipson** [comment]
Tested, LGTM, merging soon.

**Pull request merged**
