### PR TITLE
[linux] Uprev Linux kernel to 5.15.69

### PR DESCRIPTION
**Pull request by crogers1**
Signed-off-by: Chris Rogers <crogers122@gmail.com>

### CODE REVIEW

**Comment by crogers1** [comment]
https://openxt.ainfosec.com/OpenXT/auto/master/master-custom/72/

**Review by jandryuk — APPROVED** [review]
Looks ok.  I'm building locally, too.

**Comment by crogers1** [comment]
Sounds good.  Just installed the custom build and the new kernel seems to be running fine.

**Comment by jandryuk** [comment]
Will merge soon.

**Pull request merged**
