### PR TITLE
libxl: really destroy tapdevs when nothing else is using them

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1038

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Build here http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/746

**Comment by rossphilipson** [comment]
Testing...

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/754

**Comment by rossphilipson** [comment]
Ok tested, looks good. Will merge after RM signoff.

**Pull request merged**
